# Generated by Django 5.2 on 2025-05-01 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('tell', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=255)),
            ],
        ),
    ]
