# Generated by Django 5.2 on 2025-05-12 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('รหัสพนักงาน', models.CharField(max_length=10)),
                ('ชื่อ', models.CharField(max_length=255)),
                ('เบอร์โทรศัพท์', models.CharField(max_length=12)),
                ('ฝ่าย', models.CharField(max_length=100)),
                ('แผนก', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='job',
            name='tell',
        ),
        migrations.AddField(
            model_name='job',
            name='tel',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
