# Generated by Django 5.2 on 2025-05-16 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_employee_remove_job_tell_job_tel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='แผนก',
            field=models.TextField(blank=True, null=True),
        ),
    ]
