# Generated by Django 5.2 on 2025-07-06 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='ชื่อ',
            new_name='name',
        ),
    ]
