# Generated by Django 5.2 on 2025-07-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_ช_อ_employee_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='name',
            new_name='ชื่อ',
        ),
    ]
