# Generated by Django 5.2 on 2025-07-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_name_employee_ช_อ'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='แผนก',
            new_name='department',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='รหัสพนักงาน',
            new_name='employeeID',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ฝ่าย',
            new_name='group',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='ชื่อ',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='employee',
            old_name='เบอร์โทรศัพท์',
            new_name='tell',
        ),
    ]
