# Generated by Django 5.2 on 2025-12-10 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_remove_profile_bio_remove_profile_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerOperationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('time', models.TimeField(verbose_name='เวลา')),
                ('steam_flow', models.FloatField(blank=True, null=True, verbose_name='1) ไอน้ำจ่าย (T/H)')),
                ('steam_pressure', models.FloatField(blank=True, null=True, verbose_name='2) ความดันไอน้ำ (bar)')),
                ('o2_gas', models.FloatField(blank=True, null=True, verbose_name='3) O2 แก๊สออกจากเตา (%)')),
                ('feeder_speed', models.FloatField(blank=True, null=True, verbose_name='4) เครื่องป้อนกากอ้อย (%)')),
                ('damper_fdf', models.FloatField(blank=True, null=True, verbose_name='5) แดมป์เปอร์ FDF (%)')),
                ('damper_idf', models.FloatField(blank=True, null=True, verbose_name='6) แดมป์เปอร์ IDF (%)')),
                ('amp_oaf', models.FloatField(blank=True, null=True, verbose_name='7) แอมป์ OAF (Amps)')),
                ('amp_fdf', models.FloatField(blank=True, null=True, verbose_name='8) แอมป์ FDF (Amps)')),
                ('amp_idf', models.FloatField(blank=True, null=True, verbose_name='9) แอมป์ IDF (Amps)')),
                ('drum_level', models.FloatField(blank=True, null=True, verbose_name='10) ระดับน้ำหม้อบน (%)')),
                ('feed_water_valve', models.FloatField(blank=True, null=True, verbose_name='11) วาล์วน้ำป้อน (%)')),
                ('feed_water_flow', models.FloatField(blank=True, null=True, verbose_name='12) ปริมาตรน้ำป้อน (T/H)')),
                ('deaerator_level', models.FloatField(blank=True, null=True, verbose_name='13) ระดับน้ำถังดีแอร์ (%)')),
                ('deaerator_valve', models.FloatField(blank=True, null=True, verbose_name='14) วาล์วน้ำถังดีแอร์ (%)')),
                ('ph_boiler', models.FloatField(blank=True, null=True, verbose_name='15) pH น้ำในเตา')),
                ('tds_boiler', models.FloatField(blank=True, null=True, verbose_name='16) TDS น้ำในเตา (ppm)')),
                ('temp_steam', models.FloatField(blank=True, null=True, verbose_name='17) อุณหภูมิไอน้ำ (ºC)')),
                ('temp_deaerator', models.FloatField(blank=True, null=True, verbose_name='18) อุณหภูมิน้ำถังดีแอร์ (ºC)')),
                ('temp_feed_water_eco', models.FloatField(blank=True, null=True, verbose_name='19) อุณหภูมิน้ำป้อนออกอีโค (ºC)')),
                ('temp_air_out_ah', models.FloatField(blank=True, null=True, verbose_name='20) อากาศออกแอร์ฮีทเตอร์ (ºC)')),
                ('temp_gas_in_ah', models.FloatField(blank=True, null=True, verbose_name='21) แก๊สเข้าแอร์ฮีทเตอร์ (ºC)')),
                ('temp_gas_in_eco', models.FloatField(blank=True, null=True, verbose_name='22) แก๊สเข้าอีโค (ºC)')),
                ('temp_gas_stack', models.FloatField(blank=True, null=True, verbose_name='23) แก๊สออกปล่อง (ºC)')),
                ('press_furnace', models.FloatField(blank=True, null=True, verbose_name='24) ความดันในเตา (mmH₂O)')),
                ('press_gas_out_ah', models.FloatField(blank=True, null=True, verbose_name='25) ความดันแก๊สออก AH (mmH₂O)')),
                ('press_gas_out_eco', models.FloatField(blank=True, null=True, verbose_name='26) ความดันแก๊สออก Eco (mmH₂O)')),
                ('press_gas_out_dc', models.FloatField(blank=True, null=True, verbose_name='27) ความดันแก๊สออก DC (mmH₂O)')),
                ('press_wet_scrubber_1', models.FloatField(blank=True, null=True, verbose_name='28) ความดัน Wet Scrubber 1 (mmH₂O)')),
                ('press_wet_scrubber_2', models.FloatField(blank=True, null=True, verbose_name='29) ความดัน Wet Scrubber 2 (mmH₂O)')),
                ('problem_cause', models.TextField(blank=True, null=True, verbose_name='สาเหตุปัญหา/หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
