# Generated by Django 5.2.3 on 2025-12-18 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_rename_ah1_air_out_press_banpong2log_bp2_ah1_air_out_press_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KPIMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='หัวข้อ KPI')),
                ('category', models.CharField(max_length=100, verbose_name='หมวดหมู่')),
                ('target', models.FloatField(verbose_name='เป้าหมาย')),
                ('unit', models.CharField(max_length=50, verbose_name='หน่วย')),
                ('weight', models.FloatField(verbose_name='น้ำหนัก')),
                ('actual', models.FloatField(verbose_name='ผลลัพธ์ (Actual)')),
                ('score', models.IntegerField(default=0, verbose_name='คะแนนที่ได้ (1-4)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('machine', models.CharField(max_length=255, verbose_name='เครื่องจักร')),
                ('dept', models.CharField(default='ไม่ระบุ', max_length=100, verbose_name='แผนก')),
                ('problem', models.TextField(verbose_name='ปัญหาที่เกิด')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='สาเหตุ')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='การแก้ไข')),
                ('downtime_stop', models.FloatField(default=0, verbose_name='เสียเวลาหยุดหีบ (ชม.)')),
                ('downtime_reduced', models.FloatField(default=0, verbose_name='ลดรอบ (ชม.)')),
                ('downtime_non_stop', models.FloatField(default=0, verbose_name='เสียเวลาไม่หยุดหีบ (ชม.)')),
                ('category', models.CharField(choices=[('สึกหรอ', 'สึกหรอ'), ('แปลกปลอม', 'แปลกปลอม'), ('สายพาน', 'สายพาน'), ('ออยซีล', 'ออยซีล'), ('ไฟฟ้า', 'ไฟฟ้า'), ('อื่นๆ', 'อื่นๆ')], default='อื่นๆ', max_length=50, verbose_name='หัวข้อ')),
                ('is_leak', models.BooleanField(default=False, verbose_name='รั่วไหลหรือไม่')),
                ('spare_part', models.CharField(default='-', max_length=255, verbose_name='อะไหล่ที่เปลี่ยน')),
                ('qty', models.FloatField(default=0, verbose_name='จำนวน')),
                ('reporter', models.CharField(default='-', max_length=100, verbose_name='ผู้แจ้ง')),
                ('resolver', models.CharField(default='-', max_length=100, verbose_name='ผู้แก้ไข')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
