# Generated by Django 5.2.3 on 2025-12-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_kpimetric_maintenancelog'),
    ]

    operations = [
        migrations.CreateModel(
            name='MillReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('line', models.CharField(choices=[('A', 'Line A'), ('B', 'Line B')], max_length=1, verbose_name='สายการผลิต')),
                ('cane_weight', models.FloatField(default=0, verbose_name='น้ำหนักอ้อย/วัน')),
                ('target_crushing', models.FloatField(default=0, verbose_name='เป้าหีบอ้อย/วัน')),
                ('reduced_capacity_hours', models.FloatField(default=0, verbose_name='ชั่วโมงลดกำลังการผลิต')),
                ('first_mill_extraction', models.FloatField(default=0, verbose_name='1st Mill Extraction')),
                ('reduced_pol_extraction', models.FloatField(default=0, verbose_name='Reduced Pol Extraction')),
                ('overall_recovery', models.FloatField(default=0, verbose_name='Overall Recovery')),
                ('cane_preparation_index', models.FloatField(default=0, verbose_name='Cane Preparation Index')),
                ('purity_drop', models.FloatField(default=0, verbose_name='Purity Drop')),
                ('bagasse_moisture', models.FloatField(default=0, verbose_name='Bagasse Moisture')),
                ('pol_bagasse', models.FloatField(default=0, verbose_name='Pol % Bagasse')),
                ('imbibition_cane', models.FloatField(default=0, verbose_name='Imbibition % Cane')),
                ('imbibition_fiber', models.FloatField(default=0, verbose_name='Imbibition % Fiber')),
                ('loss_bagasse', models.FloatField(default=0, verbose_name='Loss in Bagasse')),
                ('downtime', models.FloatField(default=0, verbose_name='Downtime')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รายงานลูกหีบ (Mill Report)',
                'verbose_name_plural': 'รายงานลูกหีบ (Mill Reports)',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
