# Generated by Django 5.2.3 on 2025-12-21 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_millreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millreport',
            name='bagasse_moisture',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Bagasse Moisture'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='cane_preparation_index',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Cane Preparation Index'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='cane_weight',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='น้ำหนักอ้อย/วัน'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='downtime',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Downtime'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='first_mill_extraction',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='1st Mill Extraction'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='imbibition_cane',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Imbibition % Cane'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='imbibition_fiber',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Imbibition % Fiber'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='loss_bagasse',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Loss in Bagasse'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='overall_recovery',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Overall Recovery'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='pol_bagasse',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Pol % Bagasse'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='purity_drop',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Purity Drop'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='reduced_capacity_hours',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ชั่วโมงลดกำลังการผลิต'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='reduced_pol_extraction',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Reduced Pol Extraction'),
        ),
        migrations.AlterField(
            model_name='millreport',
            name='target_crushing',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='เป้าหีบอ้อย/วัน'),
        ),
    ]
