# Generated by Django 5.2.3 on 2026-01-04 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_millreport_bagasse_moisture_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BoilerDailyKPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='1. วันที่')),
                ('downtime_a', models.FloatField(default=0, verbose_name='2. % Downtime A')),
                ('downtime_b', models.FloatField(default=0, verbose_name='3. % Downtime B')),
                ('downtime_sugar_melt', models.FloatField(default=0, verbose_name='4. % Downtime ละลายน้ำตาล')),
                ('reduced_cap_a', models.FloatField(default=0, verbose_name='5. % ลดกำลังการหีบ A')),
                ('reduced_cap_b', models.FloatField(default=0, verbose_name='6. % ลดกำลังการหีบ B')),
                ('pressure_20bar', models.FloatField(default=0, verbose_name='7. แรงดันไอน้ำ Header 20 bar (bar)')),
                ('flow_20bar', models.FloatField(default=0, verbose_name='8. จ่ายไอน้ำ 20 bar (ton/hr)')),
                ('total_steam_20bar', models.FloatField(default=0, verbose_name='9. ผลรวมการผลิตไอน้ำ 20 bar (ton/day)')),
                ('pressure_40bar', models.FloatField(default=0, verbose_name='10. แรงดันไอน้ำ Header 40 bar (bar)')),
                ('flow_40bar', models.FloatField(default=0, verbose_name='11. จ่ายไอน้ำ 40 bar (ton/hr)')),
                ('total_steam_40bar', models.FloatField(default=0, verbose_name='12. ผลรวมการผลิตไอน้ำ 40 bar (ton/day)')),
                ('shredder_consumption', models.FloatField(default=0, verbose_name='13. ปริมาณการใช้เครื่องตีใบอ้อย (ton/day)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
