# Generated by Django 5.2.3 on 2026-01-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_boilerdailykpi'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='millreport',
            name='overall_recovery',
        ),
        migrations.AddField(
            model_name='millreport',
            name='trash',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='trash'),
        ),
    ]
