# Generated by Django 5.0.1 on 2026-01-14 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_remove_millreport_overall_recovery_millreport_trash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='millreport',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Mill Report', 'verbose_name_plural': 'Mill Reports'},
        ),
        migrations.RenameField(
            model_name='millreport',
            old_name='downtime',
            new_name='ccs',
        ),
    ]
