# Generated by Django 5.2.3 on 2026-01-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_millreport_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='millreport',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'รายงานลูกหีบ (Mill Report)', 'verbose_name_plural': 'รายงานลูกหีบ (Mill Reports)'},
        ),
        migrations.AlterField(
            model_name='millreport',
            name='ccs',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='ccs'),
        ),
    ]
