# Generated by Django 5.2.3 on 2026-01-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_millreport_options_alter_millreport_ccs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='millreport',
            name='reduced_capacity_hours',
        ),
    ]
