# Generated by Django 5.2.3 on 2026-01-19 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0024_remove_millreport_reduced_capacity_hours'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='yoshiminelog',
            name='yos_bagasse_moisture',
        ),
        migrations.RemoveField(
            model_name='yoshiminelog',
            name='yos_cem_so2c',
        ),
        migrations.RemoveField(
            model_name='yoshiminelog',
            name='yos_cem_sox',
        ),
        migrations.RemoveField(
            model_name='yoshiminelog',
            name='yos_fdf_amp',
        ),
        migrations.RemoveField(
            model_name='yoshiminelog',
            name='yos_fdf_damper',
        ),
        migrations.RemoveField(
            model_name='yoshiminelog',
            name='yos_idf_amp',
        ),
        migrations.RemoveField(
            model_name='yoshiminelog',
            name='yos_o2_percent',
        ),
        migrations.RemoveField(
            model_name='yoshiminelog',
            name='yos_sdf_amp',
        ),
        migrations.RemoveField(
            model_name='yoshiminelog',
            name='yos_sdf_damper',
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_ah1_gas_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H#1 Gas Outlet Pressure'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_ah2_gas_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H#2 Gas Outlet Pressure'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_cem_dust',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (Dust)'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_cem_so2',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (SO2)'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_condensate_tank_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Condensate Tank Level'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_dc_gas_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='D/C Gas Outlet Pressure'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_dc_gas_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='D/C Gas Outlet Temp'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_esp_gas_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Gas Outlet Pressure'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_fdf2_air_press',
            field=models.FloatField(blank=True, null=True, verbose_name='2nd FDF. Air Pressure'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_header_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Header Temp'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_oxygen',
            field=models.FloatField(blank=True, null=True, verbose_name='Oxygen (O2)'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_sf_air_press',
            field=models.FloatField(blank=True, null=True, verbose_name='SF. Air Pressure'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_sf_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='SF. Damper แดมป์เปอร์ลมเป่ากากอ้อย'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_steam_transform_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Steam Tremformer Level'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_steam_transform_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='Steam Tremformer Control valve'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='yos_under_gate_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='Under Gate Damper'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_ah1_air_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H# 1 Air Outlet Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_ah1_air_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H# 1 Air Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_ah2_air_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H# 2 Air Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_ah2_gas_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H#2 Gas Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_bd_ah1_in_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Blow Down Air Preheater#1 Inlet Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_bd_ah1_in_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Blow Down Air Preheater#1 Inlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_bd_ah1_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Blow Down Air Preheater#1 Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_blowdown_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='.Blow Down Flow'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_cbd_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Blow Down Flow Control Valve'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_cem_co',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (CO)'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_cem_no2',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (NO2)'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_cem_nox',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (NOX)'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_cem_o2',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (O2)'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_dea_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Deaerator Level'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_dea_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Deaerator Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_dea_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='Deaerator Control valve'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_desuperheat_in_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='.De-Superheat Inlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_desuperheat_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='De-Superheat Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_desuperheat_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='De-Superheat Flow Control Valve'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_drum_level',
            field=models.FloatField(blank=True, null=True, verbose_name='Drum Level'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_drum_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Drum Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_eco_out_gas_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Eco Outlet Gas Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_eco_out_gas_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Eco Outlet Gas Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_eco_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Eco Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_esp_c1_curr',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell1 Current'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_esp_c1_volt',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell1 Voltage'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_esp_c2_curr',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell2 Current'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_esp_c2_volt',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell2 Voltage'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_feed_water_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='Feed Water Flow'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_feed_water_in_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Feed Water Inlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_feed_water_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Feed Water Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_feed_water_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Feed Water Sum'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_furnace_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Furnace Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_gas_exit_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Gas Exit Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_gas_exit_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Gas Exit Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_idf_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='IDF. Damper'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_ins_air_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Ins. Air Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_main_feeder',
            field=models.FloatField(blank=True, null=True, verbose_name='Main Feeder'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_main_steam_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='Main Steam Flow'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_main_steam_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='Main Steam Pressure'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_main_steam_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Main Steam Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_remark',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_sh_out_gas_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='1st sH Outlet Gas Temp'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_steam_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Steam Sum'),
        ),
        migrations.AlterField(
            model_name='yoshiminelog',
            name='yos_under_grate_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Under Grate Air Pressure'),
        ),
    ]
