# Generated by Django 5.2.3 on 2026-01-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_remove_yoshiminelog_yos_bagasse_moisture_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boileroperationlog',
            name='jt_press_wet_scrubber_1',
        ),
        migrations.RemoveField(
            model_name='boileroperationlog',
            name='jt_press_wet_scrubber_2',
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_cem_co',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (CO)'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_cem_dust',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (Dust)'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_cem_no2',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (NO2)'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_cem_nox',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (NOX)'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_cem_o2',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (O2)'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_cem_so2',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (SO2)'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_inlet_stack',
            field=models.FloatField(blank=True, null=True, verbose_name='30) Inlet stack'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_inlet_wet_scrubber',
            field=models.FloatField(blank=True, null=True, verbose_name='28) Inlet wet scrubber'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_outlet_wet_scrubber',
            field=models.FloatField(blank=True, null=True, verbose_name='29) Outlet wet scrubber'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_sum_feed_water',
            field=models.FloatField(blank=True, null=True, verbose_name='SUM น้ำป้อน'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='jt_sum_steam',
            field=models.FloatField(blank=True, null=True, verbose_name='SUM ไอจ่าย'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_amp_fdf',
            field=models.FloatField(blank=True, null=True, verbose_name='8) แอมป์ พัดลมเป่า FDF'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_amp_idf',
            field=models.FloatField(blank=True, null=True, verbose_name='9) แอมป์ พัดลมดูด IDF'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_amp_oaf',
            field=models.FloatField(blank=True, null=True, verbose_name='7) แอมป์ พัดลมเป่าเย็น OAF'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_damper_fdf',
            field=models.FloatField(blank=True, null=True, verbose_name='5) แดมป์เปอร์ พัดลมเป่า FDF'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_damper_idf',
            field=models.FloatField(blank=True, null=True, verbose_name='6) แดมป์เปอร์ พัดลมดูด IDF'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_deaerator_level',
            field=models.FloatField(blank=True, null=True, verbose_name='13) ระดับน้ำถังดีแอร์'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_deaerator_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='14) วาล์วน้ำถังดีแอร์'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_drum_level',
            field=models.FloatField(blank=True, null=True, verbose_name='10) ระดับน้ำหม้อบน'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_feed_water_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='12) ปริมาตรน้ำป้อน'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_feed_water_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='11) วาล์วน้ำป้อน'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_press_furnace',
            field=models.FloatField(blank=True, null=True, verbose_name='24) ความดันในเตา'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_press_gas_out_ah',
            field=models.FloatField(blank=True, null=True, verbose_name='25) ความดันแก๊สออกแอร์ฮีทเตอร์'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_press_gas_out_dc',
            field=models.FloatField(blank=True, null=True, verbose_name='27) ความดันแก๊สออก DC'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_press_gas_out_eco',
            field=models.FloatField(blank=True, null=True, verbose_name='26) ความดันแก๊สออกจากโค'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_problem_cause',
            field=models.TextField(blank=True, null=True, verbose_name='ปัญหาและสาเหตุ'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_tds_boiler',
            field=models.FloatField(blank=True, null=True, verbose_name='16) TDS น้ำในเตา'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_temp_air_out_ah',
            field=models.FloatField(blank=True, null=True, verbose_name='20) อากาศออกแอร์ฮีทเตอร์'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_temp_deaerator',
            field=models.FloatField(blank=True, null=True, verbose_name='18) อุณหภูมิน้ำถังดีแอร์'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_temp_feed_water_eco',
            field=models.FloatField(blank=True, null=True, verbose_name='19) อุณหภูมิน้ำป้อนออกอีโค'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_temp_gas_in_ah',
            field=models.FloatField(blank=True, null=True, verbose_name='21) แก๊สเข้าแอร์ฮีทเตอร์'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_temp_gas_in_eco',
            field=models.FloatField(blank=True, null=True, verbose_name='22) แก๊สเข้าอีโค'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_temp_gas_stack',
            field=models.FloatField(blank=True, null=True, verbose_name='23) แก๊สออกปล่อง'),
        ),
        migrations.AlterField(
            model_name='boileroperationlog',
            name='jt_temp_steam',
            field=models.FloatField(blank=True, null=True, verbose_name='17) อุณหภูมิไอน้ำ'),
        ),
    ]
