# Generated by Django 5.2.3 on 2026-01-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0026_remove_boileroperationlog_jt_press_wet_scrubber_1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chengchenlog',
            name='ch_inlet_stack_press',
            field=models.FloatField(blank=True, null=True, verbose_name='27) Inlet stack gas pressure'),
        ),
        migrations.AddField(
            model_name='chengchenlog',
            name='ch_inlet_wet_scrubber_press',
            field=models.FloatField(blank=True, null=True, verbose_name='25) Inlet wet scrubber gas pressure'),
        ),
        migrations.AddField(
            model_name='chengchenlog',
            name='ch_outlet_wet_scrubber_press',
            field=models.FloatField(blank=True, null=True, verbose_name='26) Outlet wet scrubber gas pressure'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_air_heater_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='18) อากาศออกแอร์ฮีทเตอร์'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_dea_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='16) อุณหภูมิน้ำถังดีแอร์'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_drum_level',
            field=models.FloatField(blank=True, null=True, verbose_name='10) ระดับน้ำหม้อบน'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_eco_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='17) อุณหภูมิน้ำป้อนออกอีโค'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_fdf_amp',
            field=models.FloatField(blank=True, null=True, verbose_name='7) แอมป์ พัดลมเป่า (FDF)'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_fdf_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='5) แดมเปอร์ พัดลมเป่า (FDF)'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_feed_water_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='12) ปริมาตรน้ำป้อน'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_feed_water_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='11) คอลโทรลวาล์วน้ำป้อน'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_feeder_control',
            field=models.FloatField(blank=True, null=True, verbose_name='4) คอลโทรลเครื่องป้อนกากอ้อย'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_furnace_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='22) ความดันในเตา'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_gas_furnace_ah_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='19) แก๊สออกจากเตาเข้าแอร์ฮีทเตอร์'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_gas_in_eco_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='20) แก๊สเข้าอีโค'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_gas_out_dc_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='24) ความดันแก๊สออก DC'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_gas_out_eco_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='23) ความดันแก๊สออกจากอีโค'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_idf_amp',
            field=models.FloatField(blank=True, null=True, verbose_name='9) แอมป์ พัดลมดูด (IDF)'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_idf_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='6) แดมเปอร์ พัดลมดูด (IDF)'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_o2_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='3) O2 ภายในเตา'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_remark',
            field=models.TextField(blank=True, null=True, verbose_name='ปัญหาสาเหตุ/การแก้ไข'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_saf_amp_left',
            field=models.FloatField(blank=True, null=True, verbose_name='8) แอมป์ พัดลมช่วย SAF ซ้าย'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_saf_amp_right',
            field=models.FloatField(blank=True, null=True, verbose_name='8) แอมป์ พัดลมช่วย SAF ขวา'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_stack_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='21) แก๊สออกปล่อง'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_steam_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='1) ไอน้ำจ่าย'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_steam_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='2) แรงดันไอน้ำ'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_steam_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='15) อุณหภูมิไอน้ำ'),
        ),
        migrations.AlterField(
            model_name='chengchenlog',
            name='ch_tds_water',
            field=models.FloatField(blank=True, null=True, verbose_name='14) TDS น้ำในเตา'),
        ),
    ]
