# Generated by Django 5.2.3 on 2026-01-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0027_chengchenlog_ch_inlet_stack_press_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='takumalog',
            name='tk_eco_out_temp',
        ),
        migrations.RemoveField(
            model_name='takumalog',
            name='tk_gas_in_eco_temp',
        ),
        migrations.RemoveField(
            model_name='takumalog',
            name='tk_gas_out_eco_pressure',
        ),
        migrations.AddField(
            model_name='takumalog',
            name='tk_inlet_stack_press',
            field=models.FloatField(blank=True, null=True, verbose_name='24) Inlet stack gas pressure'),
        ),
        migrations.AddField(
            model_name='takumalog',
            name='tk_inlet_wet_scrubber_press',
            field=models.FloatField(blank=True, null=True, verbose_name='22) Inlet wet scrubber gas pressure'),
        ),
        migrations.AddField(
            model_name='takumalog',
            name='tk_outlet_wet_scrubber_press',
            field=models.FloatField(blank=True, null=True, verbose_name='23) Outlet wet scrubber gas pressure'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_air_heater_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='17) อากาศออกแอร์ฮีทเตอร์'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_dea_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='16) อุณหภูมิน้ำถังดีแอร์'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_drum_level',
            field=models.FloatField(blank=True, null=True, verbose_name='10) ระดับน้ำหม้อบน'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_fdf_amp',
            field=models.FloatField(blank=True, null=True, verbose_name='7) แอมป์ พัดลมเป่า (FDF)'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_fdf_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='5) แดมเปอร์ พัดลมเป่า (FDF)'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_feed_water_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='12) ปริมาตรน้ำป้อน'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_feed_water_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='11) คอลโทรลวาล์วน้ำป้อน'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_feeder_control',
            field=models.FloatField(blank=True, null=True, verbose_name='4) เครื่องป้อนกากอ้อย'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_furnace_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='20) ความดันในเตา'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_gas_furnace_ah_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='18) แก๊สออกจากเตาเข้าแอร์ฮีทเตอร์'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_gas_out_dc_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='21) ความดันแก๊สออก DC'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_idf_amp',
            field=models.FloatField(blank=True, null=True, verbose_name='9) แอมป์ พัดลมดูด (IDF)'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_idf_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='6) แดมเปอร์ พัดลมดูด (IDF)'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_o2_percent',
            field=models.FloatField(blank=True, null=True, verbose_name='3) O2 ภายในเตา'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_remark',
            field=models.TextField(blank=True, null=True, verbose_name='ปัญหาสาเหตุ / การแก้ไข'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_saf_amp_left',
            field=models.FloatField(blank=True, null=True, verbose_name='8) แอมป์ พัดลมช่วย SAF ซ้าย'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_saf_amp_right',
            field=models.FloatField(blank=True, null=True, verbose_name='8) แอมป์ พัดลมช่วย SAF ขวา'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_stack_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='19) แก๊สออกปล่อง'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_steam_flow',
            field=models.FloatField(blank=True, null=True, verbose_name='1) ไอน้ำจ่าย'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_steam_pressure',
            field=models.FloatField(blank=True, null=True, verbose_name='2) แรงดันไอน้ำ'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_steam_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='15) อุณหภูมิไอน้ำ'),
        ),
        migrations.AlterField(
            model_name='takumalog',
            name='tk_tds_water',
            field=models.FloatField(blank=True, null=True, verbose_name='14) TDS น้ำในเตา'),
        ),
    ]
