# Generated by Django 5.2.3 on 2026-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0028_remove_takumalog_tk_eco_out_temp_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banpong1log',
            name='bp1_ah2_air_out_press',
        ),
        migrations.RemoveField(
            model_name='banpong1log',
            name='bp1_esp_gas_in_press',
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_ah2_air_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H# 2 Air Outlet Temp'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_bd_ah1_in_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Blow Down Air Preheater#1 Inlet Temp'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_blowdown_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Sum Blow Down'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_cem_co',
            field=models.FloatField(blank=True, null=True, verbose_name='Comtinous Emissions Monitoring (CO)'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_cem_no2',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (NO2)'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_cem_nox',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (NOX)'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_cem_o2',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (O2)'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_cem_so2',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (SO2)'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_cem_tsp',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Emissions Monitoring (TSP)'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_esp_gas_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Gas Outlet Pressure'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_esp_gas_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Gas Outlet Temp'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_feed_water_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Feed Water Sum'),
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_steam_sum',
            field=models.FloatField(blank=True, null=True, verbose_name='Steam Sum'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_ah1_air_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H# 1 Air Outlet Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_ah1_air_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H# 1 Air Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_ah1_gas_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H#1 Gas Outlet Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_ah1_gas_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H#1 Gas Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_ah2_gas_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H#2 Gas Outlet Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_ah2_gas_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='A/H#2 Gas Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_bd_ah1_in_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Blow Down Air Preheater#1 Inlet Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_bd_ah1_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Blow Down Air Preheater#1 Outlet Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_bd_ah1_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Blow Down Air Preheater#1 Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_cbd_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='Continous Blow Down Flow Control Valve'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_dc_gas_out_press',
            field=models.FloatField(blank=True, null=True, verbose_name='D/C Gas Outlet Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_dc_gas_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='D/C Gas Outlet Temp'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_desuperheat_in_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='De-Superheat Inlet Temp.'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_desuperheat_out_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='De-Superheat Outlet Temp.'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_desuperheat_valve',
            field=models.FloatField(blank=True, null=True, verbose_name='De-Superheat Flow Control Valve'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_eco_out_gas_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Eco Outlet Gas Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_eco_out_gas_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Eco Outlet Gas Temp'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_esp_c1_curr',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell1 Current'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_esp_c1_volt',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell1 Voltage'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_esp_c2_curr',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell2 Current'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_esp_c2_volt',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell2 Voltage'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_esp_c3_curr',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell3 Current'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_esp_c3_volt',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Cell3 Voltage'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_esp_gas_in_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Esp Gas Inlet Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_faf_air_press',
            field=models.FloatField(blank=True, null=True, verbose_name='FAF. Air Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_faf_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='FAF. Damper'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_fdf2_air_press',
            field=models.FloatField(blank=True, null=True, verbose_name='2nd FDF. Air Pressure'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_fdf2_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='2nd FDF. Damper'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_fdf_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='FDF. Damper'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_feed_water_in_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Feed Water Inlet Temp.'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_idf_damper',
            field=models.FloatField(blank=True, null=True, verbose_name='IDF. Damper'),
        ),
        migrations.AlterField(
            model_name='banpong1log',
            name='bp1_under_grate_air_press',
            field=models.FloatField(blank=True, null=True, verbose_name='Under Grate Air Pressure'),
        ),
    ]
