# Generated by Django 5.2.3 on 2026-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_remove_banpong1log_bp1_ah2_air_out_press_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banpong1log',
            name='bp1_ah1_gas_out_temp',
        ),
        migrations.AddField(
            model_name='banpong1log',
            name='bp1_stack_temp',
            field=models.FloatField(blank=True, null=True, verbose_name='Stack Temp'),
        ),
    ]
