# Generated by Django 5.2.3 on 2026-03-04 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_remove_banpong1log_bp1_stack_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LatheJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_no', models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบงาน')),
                ('date', models.DateField(blank=True, null=True, verbose_name='วันที่แจ้ง')),
                ('requester', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชื่อผู้ขอ')),
                ('dept', models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนก')),
                ('tel', models.CharField(blank=True, max_length=50, null=True, verbose_name='เบอร์โทร')),
                ('machine', models.CharField(blank=True, max_length=100, null=True, verbose_name='เครื่องจักรที่ใช้ผลิต')),
                ('cust_machine', models.CharField(blank=True, max_length=100, null=True, verbose_name='เครื่องจักรลูกค้า')),
                ('topic', models.TextField(blank=True, null=True, verbose_name='รายละเอียดงาน')),
                ('job_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='ประเภทงาน')),
                ('priority', models.CharField(blank=True, max_length=50, null=True, verbose_name='ความเร่งด่วน')),
                ('req_date', models.DateField(blank=True, null=True, verbose_name='วันที่ต้องการใช้ของ')),
                ('has_drawing', models.BooleanField(default=False, verbose_name='มีแบบ Drawing')),
                ('has_sample', models.BooleanField(default=False, verbose_name='มีตัวอย่าง')),
                ('has_material', models.BooleanField(default=False, verbose_name='มีวัสดุมาให้')),
                ('plan_status', models.CharField(blank=True, max_length=50, null=True, verbose_name='สถานะพิจารณา')),
                ('plan_reject_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='เหตุผลไม่รับ')),
                ('plan_due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดส่ง')),
                ('maker', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้รับผิดชอบ')),
                ('material_cost', models.FloatField(default=0, verbose_name='ค่าวัสดุ')),
                ('hours', models.FloatField(default=0, verbose_name='เวลาทำงานรวม (ชม.)')),
                ('pieces', models.FloatField(default=1, verbose_name='จำนวน (ชิ้น)')),
                ('qc_result', models.CharField(blank=True, max_length=50, null=True, verbose_name='ผล QC')),
                ('qc_note', models.CharField(blank=True, max_length=255, null=True, verbose_name='หมายเหตุ QC')),
                ('receiver', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้รับงาน')),
                ('status', models.CharField(default='Pending', max_length=50, verbose_name='สถานะงาน')),
            ],
        ),
    ]
