# Generated by Django 5.2.3 on 2026-03-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_lathejob'),
    ]

    operations = [
        migrations.AddField(
            model_name='lathejob',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='lathe_attachments/', verbose_name='ไฟล์แนบ'),
        ),
    ]
