# Generated by Django 5.2.3 on 2026-03-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_lathejob_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lathejob',
            name='attachment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Drive File ID'),
        ),
    ]
