# Generated by Django 5.2.3 on 2026-03-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_lathejob_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='banpong1log',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะใช้งาน (Active)'),
        ),
        migrations.AddField(
            model_name='banpong2log',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะใช้งาน (Active)'),
        ),
        migrations.AddField(
            model_name='boileroperationlog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะใช้งาน (Active)'),
        ),
        migrations.AddField(
            model_name='chengchenlog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะใช้งาน (Active)'),
        ),
        migrations.AddField(
            model_name='takumalog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะใช้งาน (Active)'),
        ),
        migrations.AddField(
            model_name='yoshiminelog',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะใช้งาน (Active)'),
        ),
    ]
