# Generated by Django 5.2.3 on 2026-03-06 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_banpong1log_is_active_banpong2log_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancelog',
            name='downtime_dissolve',
            field=models.FloatField(default=0, verbose_name='เสียเวลาหยุดละลาย (ชม.)'),
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='unit',
            field=models.CharField(default='ชิ้น', max_length=50, verbose_name='หน่วย'),
        ),
        migrations.AlterField(
            model_name='maintenancelog',
            name='category',
            field=models.CharField(choices=[('สึกหรอ', 'สึกหรอตามสภาพ'), ('แม็คซีล', 'แม็คซีล (Mechanical Seal)'), ('Bearing', 'สารหล่อลื่น-Bearing'), ('สายพาน', 'สายพานหย่อน-ขาด-Alingment'), ('สิ่งแวดล้อม', 'สิ่งแวดล้อม (รั่วไหล)'), ('อุบัติเหตุ', 'อุบัติเหตุ'), ('แปลกปลอม', 'สิ่งแปลกปลอม'), ('ไฟฟ้า', 'ไฟฟ้า/Instrument'), ('อื่นๆ', 'อื่นๆ')], default='อื่นๆ', max_length=50, verbose_name='หัวข้อ'),
        ),
    ]
