# Generated by Django 5.2.3 on 2026-03-09 04:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0036_maintenancelog_downtime_dissolve_maintenancelog_unit_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('equipment_id', models.CharField(max_length=50, primary_key=True, serialize=False, verbose_name='รหัสเครื่องจักร')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อเครื่องจักร')),
                ('location', models.CharField(blank=True, max_length=255, null=True, verbose_name='ตำแหน่งที่ตั้ง')),
                ('belongs_to', models.CharField(blank=True, max_length=255, null=True, verbose_name='สังกัดเครื่องจักรหลัก')),
                ('model', models.CharField(blank=True, max_length=100, null=True, verbose_name='รุ่น')),
                ('manufacturer', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ผลิต')),
                ('serial_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='หมายเลขเครื่อง')),
                ('capacity', models.CharField(blank=True, max_length=100, null=True, verbose_name='ความจุ/อัตราไหล')),
                ('head_size', models.CharField(blank=True, max_length=100, null=True, verbose_name='ระยะส่ง/ขนาด')),
                ('rpm', models.CharField(blank=True, max_length=50, null=True, verbose_name='ความเร็วรอบ')),
                ('installation_date', models.DateField(blank=True, null=True, verbose_name='วันที่ติดตั้ง')),
                ('warranty_exp', models.DateField(blank=True, null=True, verbose_name='วันหมดประกัน')),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ราคาซื้อ')),
                ('replacement_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ราคาซ่อมทดแทน')),
                ('priority_level', models.CharField(choices=[('1', '1 - CRITICAL (กระทบการผลิตโดยตรง)'), ('2', '2 - ESSENTIAL'), ('3', '3 - GENERAL')], default='3', max_length=10, verbose_name='ระดับความสำคัญ')),
                ('mtbf', models.FloatField(default=0, verbose_name='MTBF (ชม.)')),
                ('mttr', models.FloatField(default=0, verbose_name='MTTR (ชม.)')),
                ('acc_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ค่าใช้จ่ายสะสม')),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/', verbose_name='รูปภาพเครื่องจักร')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CBMInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_type', models.CharField(choices=[('visual', 'Visual Test'), ('vibration', 'Vibration'), ('thermoscan', 'Thermoscan'), ('oil', 'Oil Analysis'), ('acoustic', 'Acoustic Emission')], max_length=20, verbose_name='ประเภทการตรวจสอบ')),
                ('inspection_date', models.DateField(verbose_name='วันที่ตรวจสอบ')),
                ('inspector_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ตรวจสอบ')),
                ('status', models.CharField(choices=[('normal', 'ปกติ (Normal)'), ('alert', 'เฝ้าระวัง (Alert)'), ('danger', 'อันตราย (Danger)'), ('na', 'ยังไม่มีข้อมูล (N/A)')], default='normal', max_length=20, verbose_name='สถานะสุขภาพ')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='รายละเอียด/หมายเหตุ')),
                ('file_attachment', models.FileField(blank=True, null=True, upload_to='cbm_files/', verbose_name='ไฟล์แนบ (PDF/Audio)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbm_inspections', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentBOM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=100, verbose_name='รหัสอะไหล่ (Part No.)')),
                ('part_name', models.CharField(max_length=255, verbose_name='ชื่ออะไหล่ (Description)')),
                ('qty', models.IntegerField(default=1, verbose_name='จำนวนที่ใช้ (Qty)')),
                ('location', models.CharField(blank=True, max_length=100, null=True, verbose_name='สถานที่เก็บ (Store/Bin)')),
                ('stock_qty', models.IntegerField(default=0, verbose_name='ยอดคงคลัง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boms', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
        ),
    ]
