# Generated by Django 5.2.3 on 2026-03-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_equipment_cbminspection_equipmentbom'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbminspection',
            name='recorder_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้บันทึกข้อมูล'),
        ),
    ]
