# Generated by Django 5.2.3 on 2026-03-11 04:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_cbminspection_recorder_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBMAcoustic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='วันที่ตรวจสอบ')),
                ('inspector', models.CharField(max_length=100, verbose_name='ผู้ตรวจสอบ')),
                ('inspection_point', models.CharField(blank=True, max_length=150, null=True, verbose_name='จุดตรวจสอบ')),
                ('decibel', models.FloatField(blank=True, null=True, verbose_name='ระดับเสียง (dB/RMS)')),
                ('sound_pattern', models.CharField(choices=[('normal', 'เสียงราบเรียบปกติ (Smooth)'), ('hissing', 'เสียงฟู่/รั่ว (Hissing)'), ('rubbing', 'เสียงเสียดสีต่อเนื่อง (Rubbing)'), ('impacting', 'เสียงกระแทก/แตกหัก (Impacting/Clicking)')], default='normal', max_length=20, verbose_name='ลักษณะเสียงที่พบ')),
                ('audio_attachment', models.FileField(blank=True, null=True, upload_to='cbm_acoustic/', verbose_name='ไฟล์บันทึกเสียง')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbm_acoustics', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
        ),
        migrations.CreateModel(
            name='CBMOilAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection_date', models.DateField(verbose_name='วันที่เก็บตัวอย่าง')),
                ('inspector', models.CharField(max_length=100, verbose_name='ผู้ตรวจสอบ')),
                ('oil_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='ชนิดน้ำมัน')),
                ('viscosity', models.FloatField(blank=True, null=True, verbose_name='ความหนืด @40°C (cSt)')),
                ('water_content', models.FloatField(blank=True, null=True, verbose_name='ปริมาณน้ำเจือปน (%)')),
                ('wear_particle', models.CharField(blank=True, max_length=100, null=True, verbose_name='ระดับอนุภาคความสึกหรอ (ISO Code)')),
                ('lab_report', models.FileField(blank=True, null=True, upload_to='cbm_oil/', verbose_name='ไฟล์ผล Lab Report (PDF)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbm_oil_analyses', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
        ),
        migrations.CreateModel(
            name='CBMThermoscan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='วันที่ถ่ายภาพ')),
                ('inspector', models.CharField(max_length=100, verbose_name='ผู้ตรวจสอบ')),
                ('location_target', models.CharField(max_length=150, verbose_name='จุดที่ถ่าย (Location Target)')),
                ('max_temp', models.FloatField(blank=True, null=True, verbose_name='อุณหภูมิสูงสุด (Max Temp °C)')),
                ('ambient_temp', models.FloatField(blank=True, null=True, verbose_name='อุณหภูมิแวดล้อม (Ambient °C)')),
                ('delta_t', models.FloatField(blank=True, null=True, verbose_name='ผลต่าง (Delta T °C)')),
                ('image_attachment', models.ImageField(blank=True, null=True, upload_to='cbm_thermoscan/', verbose_name='ภาพถ่าย IR')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbm_thermoscans', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
        ),
        migrations.CreateModel(
            name='CBMVibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='วันที่ตรวจสอบ')),
                ('inspector', models.CharField(max_length=100, verbose_name='ผู้ตรวจสอบ')),
                ('measurement_point', models.CharField(max_length=150, verbose_name='จุดที่วัด')),
                ('velocity', models.FloatField(blank=True, null=True, verbose_name='Velocity (mm/s)')),
                ('acceleration', models.FloatField(blank=True, null=True, verbose_name='Acceleration (g)')),
                ('bearing_temp', models.FloatField(blank=True, null=True, verbose_name='Bearing Temp (°C)')),
                ('status', models.CharField(choices=[('normal', 'Normal (อยู่ในเกณฑ์มาตรฐาน ISO)'), ('warning', 'Warning (เฝ้าระวัง/เริ่มมีปัญหา)'), ('alarm', 'Alarm (อันตราย/ต้องวางแผนซ่อม)')], default='normal', max_length=20, verbose_name='สถานะการประเมิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbm_vibrations', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
        ),
        migrations.CreateModel(
            name='CBMVisualTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inspection_date', models.DateField(verbose_name='วันที่ตรวจสอบ')),
                ('inspector', models.CharField(max_length=100, verbose_name='ผู้ตรวจสอบ')),
                ('overall_condition', models.CharField(choices=[('good', 'ปกติ (Good - No Action)'), ('fair', 'เฝ้าระวัง (Fair - Monitor)'), ('poor', 'ผิดปกติ (Poor - Action Required)')], default='good', max_length=20, verbose_name='สภาพโดยรวม')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='รายละเอียด/ข้อเสนอแนะ')),
                ('image_attachment', models.ImageField(blank=True, null=True, upload_to='cbm_visual/', verbose_name='รูปถ่ายหน้างาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cbm_visual_tests', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
        ),
        migrations.DeleteModel(
            name='CBMInspection',
        ),
    ]
