# Generated by Django 5.2.3 on 2026-03-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_cbmacoustic_cbmoilanalysis_cbmthermoscan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='attachment_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสไฟล์ Google Drive'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='attachment_file_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อไฟล์แนบ'),
        ),
    ]
