# Generated by Django 5.2.3 on 2026-03-12 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0040_equipment_attachment_file_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='process',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='กระบวนการ'),
        ),
    ]
