# Generated by Django 5.2.3 on 2026-03-12 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_equipment_process'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='breaker',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='เบรกเกอร์'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='motor',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='มอเตอร์ขับเคลื่อน'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='panel',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ตู้คอนโทรล'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='starter',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชุดสตาร์ท'),
        ),
    ]
