# Generated by Django 5.2.3 on 2026-03-12 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_equipment_breaker_equipment_motor_equipment_panel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='drive_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ประเภทการส่งกำลัง'),
        ),
    ]
