# Generated by Django 5.2.3 on 2026-03-12 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0043_equipment_drive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='image_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสไฟล์รูป Google Drive'),
        ),
    ]
