# Generated by Django 5.2.3 on 2026-03-13 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_equipment_image_file_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbmoilanalysis',
            name='oil_remark',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุสถานะปัจจุบันของน้ำมัน'),
        ),
    ]
