# Generated by Django 5.2.3 on 2026-03-13 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0045_cbmoilanalysis_oil_remark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbmacoustic',
            name='audio_attachment',
        ),
        migrations.RemoveField(
            model_name='cbmoilanalysis',
            name='lab_report',
        ),
        migrations.RemoveField(
            model_name='cbmthermoscan',
            name='image_attachment',
        ),
        migrations.RemoveField(
            model_name='cbmvisualtest',
            name='image_attachment',
        ),
        migrations.AddField(
            model_name='cbmacoustic',
            name='audio_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสไฟล์บันทึกเสียง (Google Drive)'),
        ),
        migrations.AddField(
            model_name='cbmoilanalysis',
            name='lab_report_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสไฟล์ Lab Report (Google Drive)'),
        ),
        migrations.AddField(
            model_name='cbmthermoscan',
            name='image_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสไฟล์ภาพถ่าย IR (Google Drive)'),
        ),
        migrations.AddField(
            model_name='cbmvisualtest',
            name='image_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='รหัสไฟล์รูปถ่าย (Google Drive)'),
        ),
    ]
