# Generated by Django 5.2.3 on 2026-03-16 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0046_remove_cbmacoustic_audio_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lathejob',
            name='sketch_image_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Sketch Image File ID'),
        ),
    ]
