# Generated by Django 5.2.3 on 2026-03-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_lathejob_created_at_lathejob_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='lathejob',
            name='log_data',
            field=models.TextField(blank=True, null=True, verbose_name='ข้อมูลประวัติการทำงาน (JSON)'),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='วันที่สร้าง'),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='วันที่แก้ไขล่าสุด'),
        ),
    ]
