# Generated by Django 5.2.3 on 2026-05-20 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_lathejob_log_data_alter_lathejob_created_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lathejob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lathejob',
            name='log_data',
        ),
        migrations.RemoveField(
            model_name='lathejob',
            name='sketch_image_id',
        ),
        migrations.RemoveField(
            model_name='lathejob',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='millreport',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mill_reports_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก'),
        ),
        migrations.AddField(
            model_name='millreport',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mill_reports_updated', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขล่าสุด'),
        ),
    ]
