# Generated by Django 5.2.14 on 2026-06-02 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_lathejob_log_data_alter_lathejob_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lathejob',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='lathejob',
            name='log_data',
        ),
        migrations.RemoveField(
            model_name='lathejob',
            name='sketch_image_id',
        ),
        migrations.RemoveField(
            model_name='lathejob',
            name='updated_at',
        ),
    ]
