# Generated by Django 5.2.14 on 2026-06-09 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0050_remove_lathejob_created_at_remove_lathejob_log_data_and_more'),
        ('myapp', '0051_repairdocument'),
    ]

    operations = [
    ]
