# Generated by Django 5.2.3 on 2026-06-22 10:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0051_repairdocument'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='รหัสสินค้า')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อรายการ')),
                ('category', models.CharField(choices=[('tools', 'เครื่องมือช่าง'), ('spares', 'อะไหล่เครื่องจักร'), ('consumables', 'วัสดุสิ้นเปลือง'), ('lubricants', 'น้ำมัน/สารเคมี')], default='consumables', max_length=20, verbose_name='หมวดหมู่')),
                ('department', models.CharField(choices=[('mill_a', 'ลูกหีบ A'), ('mill_b', 'ลูกหีบ B'), ('boiler_20', 'หม้อน้ำ 20 bar'), ('boiler_40', 'หม้อน้ำ 40 bar'), ('maintenance', 'ซ่อมบำรุงเครื่องกล'), ('lathe', 'โรงกลึง')], default='maintenance', max_length=20, verbose_name='แผนก')),
                ('unit', models.CharField(default='ชิ้น', max_length=20, verbose_name='หน่วยนับ')),
                ('stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ยอดคงเหลือ')),
                ('min_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='สต็อกขั้นต่ำ')),
                ('max_stock', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='สต็อกสูงสุด')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='ที่จัดเก็บ')),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='ราคา/หน่วย')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('linked_bom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_items', to='myapp.equipmentbom', verbose_name='ผูกกับ BOM อะไหล่')),
            ],
            options={
                'verbose_name': 'รายการคลัง (Inventory Item)',
                'verbose_name_plural': 'รายการคลัง (Inventory Items)',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='InventoryTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tx_type', models.CharField(choices=[('receive', 'รับเข้า'), ('issue', 'เบิกออก'), ('return', 'คืน'), ('adjust', 'ปรับยอด')], max_length=10, verbose_name='ประเภท')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='จำนวน')),
                ('department', models.CharField(choices=[('mill_a', 'ลูกหีบ A'), ('mill_b', 'ลูกหีบ B'), ('boiler_20', 'หม้อน้ำ 20 bar'), ('boiler_40', 'หม้อน้ำ 40 bar'), ('maintenance', 'ซ่อมบำรุงเครื่องกล'), ('lathe', 'โรงกลึง')], max_length=20, verbose_name='แผนก')),
                ('employee_name', models.CharField(blank=True, max_length=100, verbose_name='ชื่อพนักงาน')),
                ('po_number', models.CharField(blank=True, max_length=50, verbose_name='เลขที่ PO')),
                ('supplier', models.CharField(blank=True, max_length=200, verbose_name='ผู้ขาย')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ทำรายการ')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_txs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='myapp.inventoryitem', verbose_name='รายการ')),
                ('maintenance_log', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_txs', to='myapp.maintenancelog', verbose_name='ใบแจ้งซ่อมที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'ประวัติเคลื่อนไหวคลัง (Transaction)',
                'verbose_name_plural': 'ประวัติเคลื่อนไหวคลัง (Transactions)',
                'ordering': ['-created_at'],
            },
        ),
    ]
