# Generated by Django 5.2.3 on 2026-06-24 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_alter_repairdocument_doc_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipment',
            options={'verbose_name': 'เครื่องจักร', 'verbose_name_plural': 'เครื่องจักรทั้งหมด'},
        ),
        migrations.AddField(
            model_name='maintenancelog',
            name='equipment_fk',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='maintenance_logs', to='myapp.equipment', verbose_name='เครื่องจักร (FK)'),
        ),
        migrations.CreateModel(
            name='PMSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=255, verbose_name='งาน PM')),
                ('frequency_type', models.CharField(choices=[('daily', 'รายวัน'), ('weekly', 'รายสัปดาห์'), ('monthly', 'รายเดือน'), ('quarterly', 'รายไตรมาส (3 เดือน)'), ('biannual', 'ราย 6 เดือน'), ('annual', 'รายปี'), ('hours', 'ตามชั่วโมงใช้งาน')], default='monthly', max_length=20, verbose_name='ความถี่')),
                ('frequency_value', models.IntegerField(default=1, verbose_name='ค่าความถี่')),
                ('last_completed_date', models.DateField(blank=True, null=True, verbose_name='ทำ PM ล่าสุด')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดทำ PM ครั้งต่อไป')),
                ('assigned_to', models.CharField(blank=True, max_length=100, verbose_name='ผู้รับผิดชอบ')),
                ('instructions', models.TextField(blank=True, verbose_name='คำแนะนำ / ขั้นตอน')),
                ('estimated_hours', models.FloatField(default=1.0, verbose_name='เวลาที่ใช้ (ชม.)')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_schedules', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
            options={
                'verbose_name': 'แผน PM',
                'verbose_name_plural': 'แผน PM ทั้งหมด',
                'ordering': ['next_due_date', 'task_name'],
            },
        ),
    ]
