# Generated by Django 5.2.3 on 2026-06-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0052_merge_20260609_1059'),
        ('myapp', '0053_alter_repairdocument_doc_type'),
    ]

    operations = [
    ]
