# Generated by Django 5.2.3 on 2026-06-29 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0053_alter_repairdocument_doc_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้แก้ไขล่าสุด'),
        ),
    ]
