# Generated by Django 5.2.3 on 2026-07-01 10:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_add_updated_by_to_equipment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='หัวข้อ')),
                ('linked_equipment_id', models.CharField(blank=True, max_length=50, null=True, verbose_name='รหัสเครื่องจักรที่เชื่อม')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
            options={
                'verbose_name': 'ชิ้นส่วนที่เชื่อมโยง',
                'ordering': ['order', 'id'],
            },
        ),
    ]
