# Generated by Django 5.2.3 on 2026-07-02 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0055_equipmentlink'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pm_code', models.CharField(max_length=50, verbose_name='รหัสแผน PM')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อแผน/รายละเอียด')),
                ('interval_value', models.PositiveIntegerField(default=1, verbose_name='ทุกๆ')),
                ('interval_unit', models.CharField(choices=[('day', 'วัน'), ('week', 'สัปดาห์'), ('month', 'เดือน')], default='month', max_length=10, verbose_name='หน่วยความถี่')),
                ('time_of_day', models.TimeField(blank=True, null=True, verbose_name='เวลาที่ทำ')),
                ('start_date', models.DateField(verbose_name='วันที่เริ่มแผน')),
                ('last_completed_date', models.DateField(blank=True, null=True, verbose_name='วันที่ทำ PM ล่าสุด')),
                ('assigned_team', models.CharField(blank=True, max_length=100, null=True, verbose_name='ทีมผู้รับผิดชอบ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pm_plans', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
            options={
                'verbose_name': 'แผนบำรุงรักษาเชิงป้องกัน',
                'verbose_name_plural': 'แผนบำรุงรักษาเชิงป้องกัน',
                'ordering': ['pm_code'],
            },
        ),
        migrations.CreateModel(
            name='PMPlanItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='รายการที่ต้องทำ')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='myapp.pmplan', verbose_name='แผน PM')),
            ],
            options={
                'verbose_name': 'รายการตรวจใน PM',
                'verbose_name_plural': 'รายการตรวจใน PM',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wo_no', models.CharField(max_length=50, unique=True, verbose_name='เลขที่ใบสั่งซ่อม')),
                ('problem_title', models.CharField(max_length=255, verbose_name='อาการ/ปัญหา')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดเพิ่มเติม')),
                ('status', models.CharField(choices=[('pending', 'รอดำเนินการ'), ('in_progress', 'กำลังดำเนินการ'), ('completed', 'ปิดงาน')], default='pending', max_length=20, verbose_name='สถานะงาน')),
                ('current_action', models.CharField(blank=True, max_length=255, null=True, verbose_name='การดำเนินการปัจจุบัน')),
                ('progress_percent', models.PositiveIntegerField(default=0, verbose_name='ความคืบหน้า (%)')),
                ('reporter', models.CharField(max_length=100, verbose_name='ผู้แจ้ง')),
                ('reporter_dept', models.CharField(blank=True, max_length=100, null=True, verbose_name='แผนกผู้แจ้ง')),
                ('report_date', models.DateField(verbose_name='วันที่แจ้ง')),
                ('mechanic', models.CharField(blank=True, max_length=100, null=True, verbose_name='ช่างผู้รับผิดชอบ')),
                ('completed_date', models.DateField(blank=True, null=True, verbose_name='วันที่ปิดงาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_orders', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
            options={
                'verbose_name': 'ใบสั่งซ่อม',
                'verbose_name_plural': 'ใบสั่งซ่อม',
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
