# Generated by Django 5.2.3 on 2026-07-02 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0056_pmplan_pmplanitem_workorder'),
    ]

    operations = [
        migrations.CreateModel(
            name='PMPlanCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_date', models.DateField(verbose_name='วันที่ทำ PM')),
                ('completed_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ทำ PM')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='myapp.pmplan', verbose_name='แผน PM')),
            ],
            options={
                'verbose_name': 'ประวัติการทำ PM',
                'verbose_name_plural': 'ประวัติการทำ PM',
                'ordering': ['-completed_date', '-created_at'],
            },
        ),
    ]
