# Generated by Django 5.2.3 on 2026-07-02 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0054_add_equipment_fk_and_pm_schedule'),
        ('myapp', '0057_pmplancompletion'),
    ]

    operations = [
    ]
