# Generated by Django 5.2.3 on 2026-07-03 08:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0058_merge_20260702_1703'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolReadinessCheck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_date', models.DateField(verbose_name='วันที่ตรวจสอบ')),
                ('inspector', models.CharField(max_length=100, verbose_name='ผู้ตรวจสอบ')),
                ('condition_ok', models.BooleanField(default=True, verbose_name='สภาพเครื่องมือ (ไม่ชำรุด)')),
                ('calibration_ok', models.BooleanField(default=True, verbose_name='สอบเทียบ/ปรับตั้งถูกต้อง')),
                ('completeness_ok', models.BooleanField(default=True, verbose_name='อุปกรณ์/อะไหล่ประกอบครบชุด')),
                ('safety_ok', models.BooleanField(default=True, verbose_name='ปลอดภัยต่อการใช้งาน')),
                ('overall_status', models.CharField(choices=[('ready', 'พร้อมใช้งาน'), ('not_ready', 'ไม่พร้อมใช้งาน')], default='ready', max_length=10, verbose_name='สรุปผล')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_readiness_checks', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('item', models.ForeignKey(limit_choices_to={'category': 'tools'}, on_delete=django.db.models.deletion.PROTECT, related_name='readiness_checks', to='myapp.inventoryitem', verbose_name='เครื่องมือ')),
            ],
            options={
                'verbose_name': 'ตรวจสอบความพร้อมเครื่องมือ (Tool Readiness Check)',
                'verbose_name_plural': 'ตรวจสอบความพร้อมเครื่องมือ (Tool Readiness Checks)',
                'ordering': ['-check_date', '-created_at'],
            },
        ),
    ]
