# Generated by Django 5.2.3 on 2026-07-04 03:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0059_toolreadinesscheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_txs', to='myapp.equipment', verbose_name='รหัสเครื่องจักร'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='work_group',
            field=models.CharField(blank=True, max_length=100, verbose_name='กลุ่มงาน'),
        ),
    ]
