# Generated by Django 5.2.3 on 2026-07-06 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0060_inventorytransaction_equipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อหลักสูตร')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียด')),
                ('duration_days', models.DecimalField(decimal_places=1, default=1, max_digits=4, verbose_name='ระยะเวลา (วัน)')),
                ('cost_per_person', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='ค่าใช้จ่ายต่อคน (บาท)')),
                ('expiry_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='อายุใบรับรอง (เดือน) - เว้นว่างถ้าไม่หมดอายุ')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'หลักสูตรฝึกอบรม',
                'verbose_name_plural': 'หลักสูตรฝึกอบรม',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่อทักษะ')),
                ('description', models.TextField(blank=True, null=True, verbose_name='คำอธิบาย')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
            ],
            options={
                'verbose_name': 'ทักษะ (Skill Bible)',
                'verbose_name_plural': 'ทักษะ (Skill Bible)',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='TrainingExamScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveSmallIntegerField(default=1, verbose_name='ครั้งที่สอบ (0=Pre-test)')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='คะแนน')),
                ('exam_date', models.DateField(verbose_name='วันที่สอบ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_scores', to='myapp.employee', verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name': 'คะแนนสอบ Skill Bible',
                'verbose_name_plural': 'คะแนนสอบ Skill Bible',
                'ordering': ['employee__name', 'attempt_no'],
            },
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่อบรม')),
                ('training_type', models.CharField(choices=[('classroom', 'ในห้องเรียน'), ('ojt', 'OJT (หน้างานจริง)'), ('online', 'ออนไลน์')], default='classroom', max_length=20, verbose_name='ประเภทการอบรม')),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='คะแนน')),
                ('status', models.CharField(choices=[('passed', 'ผ่าน'), ('pending', 'รอประเมิน'), ('failed', 'ไม่ผ่าน')], default='pending', max_length=20, verbose_name='สถานะ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='อนุมัติโดย')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='myapp.trainingcourse', verbose_name='หลักสูตร')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_records', to='myapp.employee', verbose_name='พนักงาน')),
            ],
            options={
                'verbose_name': 'ประวัติการฝึกอบรม',
                'verbose_name_plural': 'ประวัติการฝึกอบรม',
                'ordering': ['-date'],
            },
        ),
        migrations.AddField(
            model_name='trainingcourse',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='myapp.trainingskill', verbose_name='ทักษะที่เกี่ยวข้อง'),
        ),
        migrations.CreateModel(
            name='EmployeeSkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'L0 - ยังไม่ผ่าน'), (1, 'L1 - เบื้องต้น'), (2, 'L2 - ปฏิบัติงานได้'), (3, 'L3 - ผู้เชี่ยวชาญ')], default=0, verbose_name='ระดับ')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_levels', to='myapp.employee', verbose_name='พนักงาน')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_levels', to='myapp.trainingskill', verbose_name='ทักษะ')),
            ],
            options={
                'verbose_name': 'ระดับทักษะพนักงาน',
                'verbose_name_plural': 'ระดับทักษะพนักงาน',
                'ordering': ['employee__name', 'skill__display_order'],
                'unique_together': {('employee', 'skill')},
            },
        ),
    ]
