# Generated by Django 5.2.3 on 2026-07-06 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0061_trainingcourse_trainingskill_trainingexamscore_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingCourseExamAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempt_no', models.PositiveSmallIntegerField(default=1, verbose_name='ครั้งที่สอบ')),
                ('total_questions', models.PositiveSmallIntegerField(verbose_name='จำนวนข้อทั้งหมด')),
                ('fully_correct_count', models.PositiveSmallIntegerField(verbose_name='จำนวนข้อที่ถูกต้องเต็ม 100%')),
                ('score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='คะแนนเฉลี่ย (%)')),
                ('passed', models.BooleanField(verbose_name='ผ่าน/ไม่ผ่าน')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='วันที่ส่งคำตอบ')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_attempts', to='myapp.trainingcourse', verbose_name='หลักสูตร')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_exam_attempts', to='myapp.employee', verbose_name='พนักงาน')),
                ('training_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='course_exam_attempts', to='myapp.trainingrecord', verbose_name='ประวัติการฝึกอบรมที่เกี่ยวข้อง')),
            ],
            options={
                'verbose_name': 'ผลสอบออนไลน์รายหลักสูตร',
                'verbose_name_plural': 'ผลสอบออนไลน์รายหลักสูตร',
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourseMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_type', models.CharField(choices=[('document', 'เอกสาร'), ('video', 'วิดีโอ')], max_length=20, verbose_name='ประเภทไฟล์')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่อไฟล์/หัวข้อ')),
                ('file', models.FileField(upload_to='training/materials/%Y/%m/', verbose_name='ไฟล์')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับการแสดงผล')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='myapp.trainingcourse', verbose_name='หลักสูตร')),
            ],
            options={
                'verbose_name': 'เอกสาร/วิดีโอการเรียน',
                'verbose_name_plural': 'เอกสาร/วิดีโอการเรียน',
                'ordering': ['course', 'material_type', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuizQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.TextField(verbose_name='คำถาม')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับคำถาม')),
                ('is_active', models.BooleanField(default=True, verbose_name='เปิดใช้งาน')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_questions', to='myapp.trainingcourse', verbose_name='หลักสูตร')),
            ],
            options={
                'verbose_name': 'คำถามแบบทดสอบ',
                'verbose_name_plural': 'คำถามแบบทดสอบ',
                'ordering': ['course', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingQuizChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=500, verbose_name='ตัวเลือก')),
                ('is_correct', models.BooleanField(default=False, verbose_name='คำตอบถูกต้อง')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับตัวเลือก')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='myapp.trainingquizquestion', verbose_name='คำถาม')),
            ],
            options={
                'verbose_name': 'ตัวเลือกคำถาม',
                'verbose_name_plural': 'ตัวเลือกคำถาม',
                'ordering': ['question', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='TrainingCourseExamAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_score', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='คะแนนข้อนี้ (%)')),
                ('is_fully_correct', models.BooleanField(verbose_name='ถูกต้องเต็มข้อ')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.trainingcourseexamattempt', verbose_name='ครั้งที่สอบ')),
                ('selected_choices', models.ManyToManyField(related_name='selected_in_answers', to='myapp.trainingquizchoice', verbose_name='ตัวเลือกที่เลือก')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='myapp.trainingquizquestion', verbose_name='คำถาม')),
            ],
            options={
                'verbose_name': 'คำตอบรายข้อ',
                'verbose_name_plural': 'คำตอบรายข้อ',
                'ordering': ['attempt', 'question__display_order'],
            },
        ),
    ]
