# Generated by Django 5.2.3 on 2026-07-14 05:01

from django.db import migrations, models


# แผนกเก่าที่พิมพ์ไม่ตรงกับ DEPARTMENT_CHOICES ใหม่ -> ค่าที่ตรงกัน
DEPARTMENT_NORMALIZATION = {
    'ซ่อมบำรุง': 'ซ่อมบำรุงเครื่องกล',
}


def split_name_and_normalize(apps, schema_editor):
    Employee = apps.get_model('myapp', 'employee')
    valid_departments = {
        'ลูกหีบ', 'หม้อน้ำ', 'ซ่อมบำรุงเครื่องกล', 'โรงกลึง',
    }
    for emp in Employee.objects.all():
        parts = (emp.name or '').strip().split(' ', 1)
        emp.first_name = parts[0] if parts else ''
        emp.last_name = parts[1] if len(parts) > 1 else ''

        dept = (emp.department or '').strip()
        dept = DEPARTMENT_NORMALIZATION.get(dept, dept)
        emp.department = dept if dept in valid_departments else ''

        emp.save(update_fields=['first_name', 'last_name', 'department'])


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0062_trainingcourseexamattempt_trainingcoursematerial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='', max_length=150, verbose_name='ชื่อ'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='สถานะใช้งาน'),
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='นามสกุล'),
        ),
        migrations.RunPython(split_name_and_normalize, noop_reverse),
        migrations.RemoveField(
            model_name='employee',
            name='name',
        ),
        migrations.AlterModelOptions(
            name='employee',
            options={'ordering': ['first_name', 'last_name']},
        ),
        migrations.AlterModelOptions(
            name='employeeskilllevel',
            options={'ordering': ['employee__first_name', 'employee__last_name', 'skill__display_order'], 'verbose_name': 'ระดับทักษะพนักงาน', 'verbose_name_plural': 'ระดับทักษะพนักงาน'},
        ),
        migrations.AlterModelOptions(
            name='trainingexamscore',
            options={'ordering': ['employee__first_name', 'employee__last_name', 'attempt_no'], 'verbose_name': 'คะแนนสอบ Skill Bible', 'verbose_name_plural': 'คะแนนสอบ Skill Bible'},
        ),
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('ลูกหีบ', 'ลูกหีบ (Mill)'), ('หม้อน้ำ', 'หม้อน้ำ (Boiler)'), ('ซ่อมบำรุงเครื่องกล', 'ซ่อมบำรุงเครื่องกล (Mechanical)'), ('โรงกลึง', 'โรงกลึง (Lathe)')], default='', max_length=50, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeID',
            field=models.CharField(max_length=10, verbose_name='รหัสพนักงาน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.CharField(blank=True, choices=[('ช่างฝึกหัด', 'ช่างฝึกหัด'), ('ช่างเทคนิค L1', 'ช่างเทคนิค L1'), ('ช่างเทคนิค L2', 'ช่างเทคนิค L2'), ('ช่างผู้เชี่ยวชาญ L3', 'ช่างผู้เชี่ยวชาญ L3'), ('หัวหน้าช่าง', 'หัวหน้าช่าง')], max_length=100, verbose_name='กลุ่มงาน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='tell',
            field=models.CharField(blank=True, max_length=12, verbose_name='เบอร์โทรศัพท์'),
        ),
    ]
