# Generated by Django 5.2.3 on 2026-07-14 10:00

from django.db import migrations, models


CAREER_LADDER_SEED = [
    'ช่างฝึกหัด',
    'ช่างเทคนิค L1',
    'ช่างเทคนิค L2',
    'ช่างผู้เชี่ยวชาญ L3',
    'หัวหน้าช่าง',
]


def seed_career_ladder_steps(apps, schema_editor):
    CareerLadderStep = apps.get_model('myapp', 'CareerLadderStep')
    for order, name in enumerate(CAREER_LADDER_SEED):
        CareerLadderStep.objects.create(name=name, display_order=order)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0063_employee_add_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerLadderStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ชื่อขั้น')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
            ],
            options={
                'verbose_name': 'ขั้นบันไดอาชีพ',
                'verbose_name_plural': 'ขั้นบันไดอาชีพ',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='group',
            field=models.CharField(blank=True, max_length=100, verbose_name='กลุ่มงาน'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='ยังทำงานอยู่'),
        ),
        migrations.RunPython(seed_career_ladder_steps, noop_reverse),
    ]
