# Generated by Django 5.2.3 on 2026-07-15 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0064_career_ladder_and_group_freetext'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingexamscore',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_scores', to='myapp.trainingcourse', verbose_name='หลักสูตร'),
        ),
    ]
