# Generated by Django 5.2.3 on 2026-07-16 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0065_trainingexamscore_course'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerLadderStepSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100, verbose_name='หัวข้อ')),
                ('content', models.TextField(verbose_name='เนื้อหา')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='myapp.careerladderstep', verbose_name='ขั้นบันไดอาชีพ')),
            ],
            options={
                'verbose_name': 'รายละเอียดขั้นบันไดอาชีพ',
                'verbose_name_plural': 'รายละเอียดขั้นบันไดอาชีพ',
                'ordering': ['step', 'display_order', 'id'],
            },
        ),
    ]
