# Generated by Django 5.2.3 on 2026-07-16 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0066_careerladderstepsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerladderstep',
            name='benefits',
            field=models.TextField(blank=True, null=True, verbose_name='ผลประโยชน์ที่ได้รับ'),
        ),
        migrations.AddField(
            model_name='careerladderstep',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/อื่นๆ'),
        ),
        migrations.AddField(
            model_name='careerladderstep',
            name='position_duty',
            field=models.TextField(blank=True, null=True, verbose_name='ตำแหน่งหน้าที่'),
        ),
        migrations.AddField(
            model_name='careerladderstep',
            name='scope',
            field=models.TextField(blank=True, null=True, verbose_name='ขอบเขตหน้าที่'),
        ),
        migrations.DeleteModel(
            name='CareerLadderStepSection',
        ),
    ]
