# Generated by Django 5.2.3 on 2026-07-22 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0067_careerladderstep_benefits_careerladderstep_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/', verbose_name='รูปภาพสินค้า'),
        ),
    ]
