# Generated by Django 5.2.3 on 2026-07-23 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0068_inventoryitem_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(choices=[('tools', 'เครื่องมือช่าง'), ('spares', 'อะไหล่เครื่องจักร'), ('consumables', 'วัสดุสิ้นเปลือง'), ('lubricants', 'น้ำมัน/สารเคมี'), ('steel', 'เหล็กรูปพรรณ')], default='consumables', max_length=20, verbose_name='หมวดหมู่'),
        ),
    ]
