# Generated by Django 5.2.3 on 2026-07-23 04:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0069_alter_inventoryitem_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_code', models.CharField(max_length=30, unique=True, verbose_name='รหัสหน่วย')),
                ('status', models.CharField(choices=[('available', 'พร้อมใช้งาน'), ('checked_out', 'ถูกเบิกออก'), ('maintenance', 'ซ่อมบำรุง'), ('lost', 'สูญหาย'), ('retired', 'ปลดระวาง')], default='available', max_length=20, verbose_name='สถานะ')),
                ('location', models.CharField(blank=True, max_length=100, verbose_name='ตำแหน่งที่เก็บ')),
                ('condition_note', models.TextField(blank=True, verbose_name='หมายเหตุสภาพ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(limit_choices_to={'category': 'tools'}, on_delete=django.db.models.deletion.CASCADE, related_name='tool_units', to='myapp.inventoryitem', verbose_name='ชนิดเครื่องมือ')),
            ],
            options={
                'verbose_name': 'หน่วยเครื่องมือ (Tool Unit)',
                'verbose_name_plural': 'หน่วยเครื่องมือ (Tool Units)',
                'ordering': ['item__code', 'unit_code'],
            },
        ),
        migrations.CreateModel(
            name='ToolCheckout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('borrower_name', models.CharField(max_length=100, verbose_name='ผู้เบิก')),
                ('department', models.CharField(blank=True, choices=[('mill_a', 'ลูกหีบ A'), ('mill_b', 'ลูกหีบ B'), ('boiler_20', 'หม้อน้ำ 20 bar'), ('boiler_40', 'หม้อน้ำ 40 bar'), ('maintenance', 'ซ่อมบำรุงเครื่องกล'), ('lathe', 'โรงกลึง')], max_length=20, null=True, verbose_name='แผนก')),
                ('checkout_date', models.DateField(verbose_name='วันที่เบิก')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดคืน')),
                ('return_date', models.DateField(blank=True, null=True, verbose_name='วันที่คืน')),
                ('note', models.TextField(blank=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_checkouts', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('tool_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='myapp.toolunit', verbose_name='หน่วยเครื่องมือ')),
            ],
            options={
                'verbose_name': 'การเบิก-คืนเครื่องมือ (Tool Checkout)',
                'verbose_name_plural': 'การเบิก-คืนเครื่องมือ (Tool Checkouts)',
                'ordering': ['-checkout_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='tool_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='myapp.toolunit', verbose_name='หน่วยเครื่องมือ'),
        ),
        migrations.AddField(
            model_name='toolreadinesscheck',
            name='tool_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='readiness_checks', to='myapp.toolunit', verbose_name='หน่วยเครื่องมือ'),
        ),
    ]
