# Generated by Django 5.2.3 on 2026-08-04 07:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0070_toolunit_toolcheckout_inventorytransaction_tool_unit_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_name', models.CharField(max_length=255, verbose_name='ชื่อเครื่องจักร')),
                ('model_number', models.CharField(blank=True, default='', max_length=100, verbose_name='รุ่น/Model')),
                ('department', models.CharField(choices=[('ลูกหีบ', 'ลูกหีบ (Mill)'), ('หม้อน้ำ', 'หม้อน้ำ (Boiler)'), ('ซ่อมบำรุงเครื่องกล', 'ซ่อมบำรุงเครื่องกล (Mechanical)'), ('โรงกลึง', 'โรงกลึง (Lathe)')], max_length=50, verbose_name='แผนก')),
                ('prepared_by', models.CharField(blank=True, default='', max_length=150, verbose_name='ผู้จัดทำ')),
                ('doc_no', models.CharField(blank=True, default='', max_length=100, verbose_name='เลขที่เอกสาร')),
                ('revision', models.CharField(blank=True, default='', max_length=20, verbose_name='ฉบับแก้ไข (Rev.)')),
                ('doc_date', models.DateField(blank=True, null=True, verbose_name='วันที่จัดทำ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manuals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
            ],
            options={
                'verbose_name': 'คู่มือปฏิบัติงานเครื่องจักร',
                'verbose_name_plural': 'คู่มือปฏิบัติงานเครื่องจักร',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='ManualJsaSsopStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, max_length=100, null=True, verbose_name='ระยะ (ก่อน/ขณะ/หลังปฏิบัติงาน)')),
                ('step_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้อขั้นตอน')),
                ('action', models.TextField(blank=True, null=True, verbose_name='ขั้นตอนการปฏิบัติ (SSOP)')),
                ('tools', models.TextField(blank=True, null=True, verbose_name='อุปกรณ์/เครื่องมือที่ต้องใช้')),
                ('hazard', models.TextField(blank=True, null=True, verbose_name='อันตรายที่อาจเกิดขึ้น (JSA)')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='มาตรการป้องกันอันตราย (JSA)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jsa_ssop_steps', to='myapp.manual', verbose_name='คู่มือ')),
            ],
            options={
                'verbose_name': 'JSA & SSOP',
                'verbose_name_plural': 'JSA & SSOP',
                'ordering': ['manual', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ManualMaintenanceDailyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField(blank=True, null=True, verbose_name='จุดตรวจสอบ')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียดการตรวจ')),
                ('fix', models.TextField(blank=True, null=True, verbose_name='การแก้ไข')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_daily_items', to='myapp.manual', verbose_name='คู่มือ')),
            ],
            options={
                'verbose_name': 'การบำรุงรักษาประจำวัน',
                'verbose_name_plural': 'การบำรุงรักษาประจำวัน',
                'ordering': ['manual', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ManualMaintenancePeriodicItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=255, null=True, verbose_name='รายการ')),
                ('interval', models.CharField(blank=True, max_length=100, null=True, verbose_name='รอบเวลา')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_periodic_items', to='myapp.manual', verbose_name='คู่มือ')),
            ],
            options={
                'verbose_name': 'การบำรุงรักษาตามคาบเวลา',
                'verbose_name_plural': 'การบำรุงรักษาตามคาบเวลา',
                'ordering': ['manual', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ManualOperatingStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้อขั้นตอน')),
                ('description', models.TextField(blank=True, null=True, verbose_name='รายละเอียดขั้นตอน')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_steps', to='myapp.manual', verbose_name='คู่มือ')),
            ],
            options={
                'verbose_name': 'ขั้นตอนการใช้งาน',
                'verbose_name_plural': 'ขั้นตอนการใช้งาน',
                'ordering': ['manual', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ManualPartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label_th', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อชิ้นส่วน (ไทย)')),
                ('label_en', models.CharField(blank=True, max_length=200, null=True, verbose_name='ชื่อชิ้นส่วน (English)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='part_items', to='myapp.manual', verbose_name='คู่มือ')),
            ],
            options={
                'verbose_name': 'ชื่อชิ้นส่วน',
                'verbose_name_plural': 'ชื่อชิ้นส่วน',
                'ordering': ['manual', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ManualPrecheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.TextField(blank=True, null=True, verbose_name='จุดตรวจสอบ')),
                ('detail', models.TextField(blank=True, null=True, verbose_name='รายละเอียดการตรวจสอบ')),
                ('fix', models.TextField(blank=True, null=True, verbose_name='การแก้ไข')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precheck_items', to='myapp.manual', verbose_name='คู่มือ')),
            ],
            options={
                'verbose_name': 'รายการตรวจสอบก่อนใช้งาน',
                'verbose_name_plural': 'รายการตรวจสอบก่อนใช้งาน',
                'ordering': ['manual', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ManualSafetyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(blank=True, null=True, verbose_name='ขั้นตอนการปฏิบัติงาน')),
                ('hazard', models.TextField(blank=True, null=True, verbose_name='อันตรายที่อาจเกิดขึ้น')),
                ('measure', models.TextField(blank=True, null=True, verbose_name='มาตรการป้องกันอันตราย')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='safety_items', to='myapp.manual', verbose_name='คู่มือ')),
            ],
            options={
                'verbose_name': 'ข้อควรระวังด้านความปลอดภัย',
                'verbose_name_plural': 'ข้อควรระวังด้านความปลอดภัย',
                'ordering': ['manual', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ManualSpecItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True, verbose_name='รายการ')),
                ('value', models.CharField(blank=True, max_length=255, null=True, verbose_name='ค่า')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spec_items', to='myapp.manual', verbose_name='คู่มือ')),
            ],
            options={
                'verbose_name': 'ข้อมูลจำเพาะ',
                'verbose_name_plural': 'ข้อมูลจำเพาะ',
                'ordering': ['manual', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='ManualTroubleshootItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('problem', models.TextField(blank=True, null=True, verbose_name='ปัญหา')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='สาเหตุ')),
                ('solution', models.TextField(blank=True, null=True, verbose_name='วิธีแก้ไข')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='troubleshoot_items', to='myapp.manual', verbose_name='คู่มือ')),
            ],
            options={
                'verbose_name': 'การแก้ไขปัญหาเบื้องต้น',
                'verbose_name_plural': 'การแก้ไขปัญหาเบื้องต้น',
                'ordering': ['manual', 'display_order'],
            },
        ),
    ]
