# Generated by Django 5.2.3 on 2026-08-06 10:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0071_manual_manualjsassopstep_manualmaintenancedailyitem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyManual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(choices=[('ลูกหีบ', 'ลูกหีบ (Mill)'), ('หม้อน้ำ', 'หม้อน้ำ (Boiler)'), ('ซ่อมบำรุงเครื่องกล', 'ซ่อมบำรุงเครื่องกล (Mechanical)'), ('โรงกลึง', 'โรงกลึง (Lathe)')], max_length=50, verbose_name='แผนก')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='safety_manuals', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
            ],
            options={
                'verbose_name': 'คู่มือความปลอดภัย',
                'verbose_name_plural': 'คู่มือความปลอดภัย',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SafetyManualStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, max_length=100, null=True, verbose_name='ระยะ (ก่อน/ขณะ/หลังปฏิบัติงาน)')),
                ('step_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้อขั้นตอน')),
                ('action', models.TextField(blank=True, null=True, verbose_name='ขั้นตอนการปฏิบัติ (SSOP)')),
                ('tools', models.TextField(blank=True, null=True, verbose_name='อุปกรณ์/เครื่องมือที่ต้องใช้')),
                ('hazard', models.TextField(blank=True, null=True, verbose_name='อันตรายที่อาจเกิดขึ้น (JSA)')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='มาตรการป้องกันอันตราย (JSA)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('safety_manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jsa_ssop_steps', to='myapp.safetymanual', verbose_name='คู่มือความปลอดภัย')),
            ],
            options={
                'verbose_name': 'ขั้นตอน JSA & SSOP',
                'verbose_name_plural': 'ขั้นตอน JSA & SSOP',
                'ordering': ['safety_manual', 'display_order'],
            },
        ),
        migrations.DeleteModel(
            name='ManualJsaSsopStep',
        ),
    ]
