# Generated by Django 5.2.3 on 2026-08-06 10:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0072_safetymanual_safetymanualstep_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetymanual',
            name='department',
        ),
        migrations.AddField(
            model_name='safetymanual',
            name='job_name',
            field=models.CharField(default='', max_length=255, verbose_name='ชื่องาน'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='safetymanual',
            name='prepared_by',
            field=models.CharField(blank=True, default='', max_length=150, verbose_name='ผู้จัดทำ'),
        ),
        migrations.CreateModel(
            name='SafetyManualJsaItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, max_length=100, null=True, verbose_name='ระยะ (ก่อน/ขณะ/หลังปฏิบัติงาน)')),
                ('step_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้อขั้นตอนงาน')),
                ('hazard', models.TextField(blank=True, null=True, verbose_name='อันตรายที่อาจเกิดขึ้น')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='มาตรการป้องกันอันตราย')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('safety_manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jsa_items', to='myapp.safetymanual', verbose_name='คู่มือความปลอดภัย')),
            ],
            options={
                'verbose_name': 'รายการ JSA',
                'verbose_name_plural': 'รายการ JSA',
                'ordering': ['safety_manual', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SafetyManualSsopStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(blank=True, max_length=100, null=True, verbose_name='ระยะ (ก่อน/ขณะ/หลังปฏิบัติงาน)')),
                ('step_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='หัวข้อขั้นตอน')),
                ('action', models.TextField(blank=True, null=True, verbose_name='ขั้นตอนการปฏิบัติ')),
                ('tools', models.TextField(blank=True, null=True, verbose_name='อุปกรณ์/เครื่องมือที่ต้องใช้')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('safety_manual', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ssop_steps', to='myapp.safetymanual', verbose_name='คู่มือความปลอดภัย')),
            ],
            options={
                'verbose_name': 'ขั้นตอน SSOP',
                'verbose_name_plural': 'ขั้นตอน SSOP',
                'ordering': ['safety_manual', 'display_order'],
            },
        ),
        migrations.DeleteModel(
            name='SafetyManualStep',
        ),
    ]
