# Generated by Django 5.2.3 on 2026-08-10 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0073_remove_safetymanual_department_safetymanual_job_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetymanualjsaitem',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='safetymanualssopstep',
            name='phase',
        ),
        migrations.RemoveField(
            model_name='safetymanualssopstep',
            name='tools',
        ),
        migrations.AddField(
            model_name='safetymanualjsaitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_jsa/', verbose_name='รูปภาพ'),
        ),
        migrations.AddField(
            model_name='safetymanualssopstep',
            name='image_illustration',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_ssop/', verbose_name='รูปภาพประกอบ'),
        ),
        migrations.AddField(
            model_name='safetymanualssopstep',
            name='image_tools',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_ssop/', verbose_name='รูปภาพอุปกรณ์/เครื่องมือที่ต้องใช้'),
        ),
        migrations.AlterField(
            model_name='safetymanualjsaitem',
            name='step_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ขั้นตอนการปฏิบัติงาน'),
        ),
        migrations.AlterField(
            model_name='safetymanualssopstep',
            name='step_title',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ขั้นตอน'),
        ),
    ]
