# Generated by Django 5.2.3 on 2026-08-15 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0074_remove_safetymanualjsaitem_phase_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyManualEquipmentOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='ชื่ออุปกรณ์')),
                ('icon', models.CharField(default='wrench', max_length=50, verbose_name='ชื่อไอคอน (Lucide icon name)')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
            ],
            options={
                'verbose_name': 'ตัวเลือกอุปกรณ์/PPE',
                'verbose_name_plural': 'ตัวเลือกอุปกรณ์/PPE',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='safetymanual',
            name='department',
            field=models.CharField(blank=True, choices=[('ลูกหีบ', 'ลูกหีบ (Mill)'), ('หม้อน้ำ', 'หม้อน้ำ (Boiler)'), ('ซ่อมบำรุงเครื่องกล', 'ซ่อมบำรุงเครื่องกล (Mechanical)'), ('โรงกลึง', 'โรงกลึง (Lathe)')], max_length=50, null=True, verbose_name='แผนก'),
        ),
        migrations.AddField(
            model_name='safetymanual',
            name='manual_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่'),
        ),
        migrations.AddField(
            model_name='safetymanual',
            name='purpose',
            field=models.TextField(blank=True, null=True, verbose_name='จุดประสงค์'),
        ),
        migrations.AddField(
            model_name='safetymanualjsaitem',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_jsa/', verbose_name='รูปภาพ 2'),
        ),
        migrations.AddField(
            model_name='safetymanualjsaitem',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_jsa/', verbose_name='รูปภาพ 3'),
        ),
        migrations.AddField(
            model_name='safetymanualjsaitem',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_jsa/', verbose_name='รูปภาพ 4'),
        ),
        migrations.AddField(
            model_name='safetymanualjsaitem',
            name='phase',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='กลุ่มขั้นตอน'),
        ),
        migrations.AddField(
            model_name='safetymanualssopstep',
            name='image_illustration_2',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_ssop/', verbose_name='รูปภาพประกอบ 2'),
        ),
        migrations.AddField(
            model_name='safetymanualssopstep',
            name='image_illustration_3',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_ssop/', verbose_name='รูปภาพประกอบ 3'),
        ),
        migrations.AddField(
            model_name='safetymanualssopstep',
            name='image_illustration_4',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_ssop/', verbose_name='รูปภาพประกอบ 4'),
        ),
        migrations.AddField(
            model_name='safetymanualssopstep',
            name='phase',
            field=models.CharField(blank=True, choices=[('ก่อนปฏิบัติงาน', 'ก่อนปฏิบัติงาน'), ('ขณะปฏิบัติงาน', 'ขณะปฏิบัติงาน'), ('เมื่อเลิกงาน', 'เมื่อเลิกงาน')], max_length=50, null=True, verbose_name='ระยะ'),
        ),
        migrations.AlterField(
            model_name='safetymanualssopstep',
            name='image_tools',
            field=models.ImageField(blank=True, null=True, upload_to='safety_manual_ssop/', verbose_name='รูปอุปกรณ์อื่นๆ (ถ้ามี)'),
        ),
        migrations.AddField(
            model_name='safetymanualssopstep',
            name='equipment_items',
            field=models.ManyToManyField(blank=True, to='myapp.safetymanualequipmentoption', verbose_name='อุปกรณ์/เครื่องมือที่ต้องใช้'),
        ),
    ]
