# Generated by Django 5.2.3 on 2026-08-15 09:30

from django.db import migrations

EQUIPMENT_OPTIONS = [
    ('หมวกนิรภัย', 'hard-hat', 10),
    ('ถุงมือผ้า/ถุงมือหนัง', 'hand', 20),
    ('รองเท้าเซฟตี้', 'footprints', 30),
    ('แว่นตานิรภัย', 'glasses', 40),
    ('ชุดประแจ', 'wrench', 50),
    ('สลิง/โซ่ยก', 'link', 60),
    ('บันได', 'package', 70),
    ('ใบอนุญาตทำงาน (Work Permit)', 'clipboard-check', 80),
    ('กุญแจล็อค (Lock-out Tag-out)', 'lock', 90),
    ('เข็มขัดนิรภัย', 'shield', 100),
    ('หน้ากากกันฝุ่น', 'package', 110),
    ('ที่อุดหู', 'ear-off', 120),
]


def seed_equipment_options(apps, schema_editor):
    SafetyManualEquipmentOption = apps.get_model('myapp', 'SafetyManualEquipmentOption')
    for name, icon, display_order in EQUIPMENT_OPTIONS:
        SafetyManualEquipmentOption.objects.get_or_create(
            name=name, defaults={'icon': icon, 'display_order': display_order}
        )


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0075_safetymanualequipmentoption_safetymanual_department_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_equipment_options, migrations.RunPython.noop),
    ]
