# Generated by Django 5.2.3 on 2026-08-18 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0076_seed_safety_manual_equipment_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='SafetyManualJsaHazard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.TextField(blank=True, null=True, verbose_name='อันตรายที่อาจเกิดขึ้น')),
                ('prevention', models.TextField(blank=True, null=True, verbose_name='มาตรการป้องกันอันตราย')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('jsa_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hazards', to='myapp.safetymanualjsaitem', verbose_name='รายการ JSA')),
            ],
            options={
                'verbose_name': 'อันตราย/มาตรการป้องกัน (JSA)',
                'verbose_name_plural': 'อันตราย/มาตรการป้องกัน (JSA)',
                'ordering': ['jsa_item', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='SafetyManualJsaImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='safety_manual_jsa/', verbose_name='รูปภาพ')),
                ('display_order', models.PositiveIntegerField(default=0, verbose_name='ลำดับ')),
                ('jsa_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.safetymanualjsaitem', verbose_name='รายการ JSA')),
            ],
            options={
                'verbose_name': 'รูปภาพ JSA',
                'verbose_name_plural': 'รูปภาพ JSA',
                'ordering': ['jsa_item', 'display_order'],
            },
        ),
    ]
