# Generated by Django 5.2.3 on 2026-08-18 12:08

from django.db import migrations


def migrate_jsa_hazard_and_images(apps, schema_editor):
    SafetyManualJsaItem = apps.get_model('myapp', 'SafetyManualJsaItem')
    SafetyManualJsaHazard = apps.get_model('myapp', 'SafetyManualJsaHazard')
    SafetyManualJsaImage = apps.get_model('myapp', 'SafetyManualJsaImage')

    for item in SafetyManualJsaItem.objects.all():
        if (item.hazard and item.hazard.strip()) or (item.prevention and item.prevention.strip()):
            SafetyManualJsaHazard.objects.create(
                jsa_item=item, hazard=item.hazard, prevention=item.prevention, display_order=0,
            )
        order = 0
        for field_name in ['image', 'image_2', 'image_3', 'image_4']:
            file_field = getattr(item, field_name)
            if file_field:
                SafetyManualJsaImage.objects.create(
                    jsa_item=item, image=file_field.name, display_order=order,
                )
                order += 1


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0077_safetymanualjsahazard_safetymanualjsaimage'),
    ]

    operations = [
        migrations.RunPython(migrate_jsa_hazard_and_images, migrations.RunPython.noop),
    ]
