# Generated by Django 5.2.3 on 2026-08-18 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0078_migrate_jsa_hazard_and_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetymanualjsaitem',
            name='hazard',
        ),
        migrations.RemoveField(
            model_name='safetymanualjsaitem',
            name='image',
        ),
        migrations.RemoveField(
            model_name='safetymanualjsaitem',
            name='image_2',
        ),
        migrations.RemoveField(
            model_name='safetymanualjsaitem',
            name='image_3',
        ),
        migrations.RemoveField(
            model_name='safetymanualjsaitem',
            name='image_4',
        ),
        migrations.RemoveField(
            model_name='safetymanualjsaitem',
            name='prevention',
        ),
    ]
