# Generated by Django 5.2.3 on 2026-08-19 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0079_remove_safetymanualjsaitem_hazard_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='safetymanualssopstep',
            name='safety_manual',
        ),
        migrations.RemoveField(
            model_name='safetymanualjsaitem',
            name='safety_manual',
        ),
        migrations.RemoveField(
            model_name='safetymanualssopstep',
            name='equipment_items',
        ),
        migrations.RemoveField(
            model_name='safetymanualjsahazard',
            name='jsa_item',
        ),
        migrations.RemoveField(
            model_name='safetymanualjsaimage',
            name='jsa_item',
        ),
        migrations.DeleteModel(
            name='SafetyManual',
        ),
        migrations.DeleteModel(
            name='SafetyManualEquipmentOption',
        ),
        migrations.DeleteModel(
            name='SafetyManualSsopStep',
        ),
        migrations.DeleteModel(
            name='SafetyManualJsaHazard',
        ),
        migrations.DeleteModel(
            name='SafetyManualJsaImage',
        ),
        migrations.DeleteModel(
            name='SafetyManualJsaItem',
        ),
    ]
