# Generated by Django 5.2.3 on 2026-08-27 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0080_remove_safetymanualssopstep_safety_manual_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cbmvibration',
            name='acceleration',
        ),
        migrations.RemoveField(
            model_name='cbmvibration',
            name='bearing_temp',
        ),
        migrations.RemoveField(
            model_name='cbmvibration',
            name='velocity',
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='amp',
            field=models.FloatField(blank=True, null=True, verbose_name='Amp'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='de_a',
            field=models.FloatField(blank=True, null=True, verbose_name='DE (A)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='de_ge',
            field=models.FloatField(blank=True, null=True, verbose_name='DE (gE)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='de_h',
            field=models.FloatField(blank=True, null=True, verbose_name='DE (H)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='de_m',
            field=models.FloatField(blank=True, null=True, verbose_name='DE (M)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='de_v',
            field=models.FloatField(blank=True, null=True, verbose_name='DE (V)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='nde_a',
            field=models.FloatField(blank=True, null=True, verbose_name='NDE (A)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='nde_ge',
            field=models.FloatField(blank=True, null=True, verbose_name='NDE (gE)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='nde_h',
            field=models.FloatField(blank=True, null=True, verbose_name='NDE (H)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='nde_m',
            field=models.FloatField(blank=True, null=True, verbose_name='NDE (M)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='nde_v',
            field=models.FloatField(blank=True, null=True, verbose_name='NDE (V)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='temp_de',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp.(DE)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='temp_frame',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp.(FRAME)'),
        ),
        migrations.AddField(
            model_name='cbmvibration',
            name='temp_nde',
            field=models.FloatField(blank=True, null=True, verbose_name='Temp.(NDE)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='power_kw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='Power (kW)'),
        ),
        migrations.AddField(
            model_name='equipment',
            name='rpm_input',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='ความเร็วรอบเข้า (RPM)'),
        ),
        migrations.AlterField(
            model_name='cbmvibration',
            name='measurement_point',
            field=models.CharField(max_length=150, verbose_name='หมายเหตุ (Note)'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='rpm',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='ความเร็วรอบออก (RPM)'),
        ),
    ]
