# Generated by Django 5.2.3 on 2026-08-27 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0081_remove_cbmvibration_acceleration_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่องาน')),
                ('assignee', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้รับผิดชอบ')),
                ('status', models.CharField(choices=[('todo', 'Todo'), ('doing', 'Doing'), ('done', 'Done')], default='todo', max_length=10, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/ปัญหา')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='machine_tasks', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
            options={
                'verbose_name': 'งานเตรียมความพร้อมเครื่องจักร',
                'verbose_name_plural': 'งานเตรียมความพร้อมเครื่องจักร',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MachineTaskVibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phase', models.CharField(choices=[('no_load', 'เดินเครื่องตัวเปล่า'), ('loaded', 'เดินเครื่องจริง')], max_length=10, verbose_name='ช่วงการทดสอบ')),
                ('inspection_date', models.DateField(verbose_name='วันที่ตรวจสอบ')),
                ('inspector', models.CharField(max_length=100, verbose_name='ผู้ตรวจสอบ')),
                ('amp', models.FloatField(blank=True, null=True, verbose_name='Amp')),
                ('de_ge', models.FloatField(blank=True, null=True, verbose_name='DE (gE)')),
                ('de_v', models.FloatField(blank=True, null=True, verbose_name='DE (V)')),
                ('de_h', models.FloatField(blank=True, null=True, verbose_name='DE (H)')),
                ('de_a', models.FloatField(blank=True, null=True, verbose_name='DE (A)')),
                ('de_m', models.FloatField(blank=True, null=True, verbose_name='DE (M)')),
                ('nde_ge', models.FloatField(blank=True, null=True, verbose_name='NDE (gE)')),
                ('nde_v', models.FloatField(blank=True, null=True, verbose_name='NDE (V)')),
                ('nde_h', models.FloatField(blank=True, null=True, verbose_name='NDE (H)')),
                ('nde_a', models.FloatField(blank=True, null=True, verbose_name='NDE (A)')),
                ('nde_m', models.FloatField(blank=True, null=True, verbose_name='NDE (M)')),
                ('temp_de', models.FloatField(blank=True, null=True, verbose_name='Temp.(DE)')),
                ('temp_frame', models.FloatField(blank=True, null=True, verbose_name='Temp.(FRAME)')),
                ('temp_nde', models.FloatField(blank=True, null=True, verbose_name='Temp.(NDE)')),
                ('status', models.CharField(choices=[('normal', 'Normal (อยู่ในเกณฑ์มาตรฐาน ISO)'), ('warning', 'Warning (เฝ้าระวัง/เริ่มมีปัญหา)'), ('alarm', 'Alarm (อันตราย/ต้องวางแผนซ่อม)')], default='normal', max_length=20, verbose_name='สถานะการประเมิน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vibration_readings', to='myapp.machinetask', verbose_name='งาน')),
            ],
            options={
                'verbose_name': 'ข้อมูล Vibration งานเตรียมความพร้อม',
                'verbose_name_plural': 'ข้อมูล Vibration งานเตรียมความพร้อม',
                'ordering': ['phase'],
                'unique_together': {('task', 'phase')},
            },
        ),
    ]
