# Generated by Django 5.2.3 on 2026-09-01 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0082_machinetask_machinetaskvibration'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetask',
            name='actual_current',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='กระแสใช้งานจริง (A)'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='control_dcs_ok',
            field=models.BooleanField(default=False, verbose_name='DCS'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='control_local_ok',
            field=models.BooleanField(default=False, verbose_name='Local'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='control_remote_ok',
            field=models.BooleanField(default=False, verbose_name='Remote'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='participant_control',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ร่วมทดสอบ - คอนโทรล'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='participant_electrical',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ร่วมทดสอบ - ไฟฟ้า'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='participant_maintenance',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ร่วมทดสอบ - ซ่อมบำรุง'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='participant_motor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ร่วมทดสอบ - มอเตอร์'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='participant_user',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้ร่วมทดสอบ - ผู้ใช้งาน'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='rotation_direction_ok',
            field=models.BooleanField(default=False, verbose_name='ทิศทางการหมุนถูกต้อง'),
        ),
        migrations.AddField(
            model_name='machinetask',
            name='start_test_date',
            field=models.DateField(blank=True, null=True, verbose_name='วันที่จะเริ่มทดสอบ'),
        ),
        migrations.AlterField(
            model_name='machinetask',
            name='status',
            field=models.CharField(choices=[('todo', 'Alignment'), ('doing', 'Ready'), ('done', 'Finish')], default='todo', max_length=10, verbose_name='สถานะ'),
        ),
    ]
