# Generated by Django 5.2.3 on 2026-09-01 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0083_machinetask_actual_current_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='machinetask',
            name='updated_by',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้แก้ไขล่าสุด'),
        ),
        migrations.AlterField(
            model_name='machinetask',
            name='status',
            field=models.CharField(choices=[('wait', 'Wait'), ('todo', 'Alignment'), ('doing', 'Ready'), ('done', 'Finish')], default='wait', max_length=10, verbose_name='สถานะ'),
        ),
    ]
