# Generated by Django 5.2.3 on 2026-09-01 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0084_machinetask_updated_by_alter_machinetask_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='ชื่อกระบวนการ')),
                ('is_active', models.BooleanField(default=True, verbose_name='ใช้งานอยู่')),
            ],
            options={
                'verbose_name': 'กระบวนการ (Process Category)',
                'verbose_name_plural': 'กระบวนการ (Process Category)',
                'ordering': ['name'],
            },
        ),
    ]
