# Generated by Django 5.2.3 on 2026-09-04 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0086_seed_process_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingrecord',
            name='video_completed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='วันที่ดูวีดีโอครบ (พร้อมสอบ)'),
        ),
    ]
