# Generated by Django 5.2.3 on 2026-09-11 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0088_seed_training_skill'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='รหัส/ทะเบียนรถ')),
                ('vehicle_type', models.CharField(choices=[('รถเครน 25 ตัน', 'รถเครน 25 ตัน'), ('รถเครน 35 ตัน', 'รถเครน 35 ตัน'), ('รถเครน 45 ตัน', 'รถเครน 45 ตัน'), ('รถเครน >45 ตัน', 'รถเครน >45 ตัน'), ('รถเฮี๊ยบ', 'รถเฮี๊ยบ'), ('รถตัก', 'รถตัก'), ('รถน้ำ', 'รถน้ำ'), ('รถสิบล้อ(ดั๊มพ์+มีฝาท้าย)', 'รถสิบล้อ(ดั๊มพ์+มีฝาท้าย)'), ('รถสิบล้อ(ดั๊มพ์+ไม่มีฝาท้าย)', 'รถสิบล้อ(ดั๊มพ์+ไม่มีฝาท้าย)'), ('รถแบ็คโฮ', 'รถแบ็คโฮ'), ('รถไถ', 'รถไถ'), ('โฟล์คลิฟ', 'โฟล์คลิฟ'), ('รถห่างปลา', 'รถห่างปลา')], max_length=50, verbose_name='ประเภทเครื่องจักร')),
                ('readiness_status', models.CharField(choices=[('ready', 'พร้อมทำงาน'), ('not_ready', 'ไม่พร้อมทำงาน')], default='ready', max_length=10, verbose_name='สถานะความพร้อม')),
                ('not_ready_reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='เหตุผลที่ไม่พร้อมทำงาน')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'รถบริการ',
                'verbose_name_plural': 'ทะเบียนรถบริการ',
                'ordering': ['vehicle_type', 'code'],
            },
        ),
        migrations.CreateModel(
            name='VehicleBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_type', models.CharField(choices=[('planned', 'จองรถในแผนงานประจำสัปดาห์'), ('urgent', 'จองรถนอกแผน (งานด่วน)')], default='planned', max_length=10, verbose_name='ประเภทการจอง')),
                ('division', models.CharField(choices=[('ผลิต', 'ผลิต'), ('วิศวกรรมจักรกล', 'วิศวกรรมจักรกล'), ('วิศวกรรมไฟฟ้า', 'วิศวกรรมไฟฟ้า')], max_length=20, verbose_name='ฝ่าย')),
                ('department', models.CharField(max_length=100, verbose_name='แผนก')),
                ('requester_name', models.CharField(max_length=100, verbose_name='ชื่อผู้ขอใช้')),
                ('date_needed', models.DateField(verbose_name='วันที่ต้องการใช้งาน')),
                ('start_time', models.TimeField(verbose_name='เวลาเริ่ม')),
                ('end_time', models.TimeField(verbose_name='เวลาเสร็จ')),
                ('vehicle_type', models.CharField(choices=[('รถเครน 25 ตัน', 'รถเครน 25 ตัน'), ('รถเครน 35 ตัน', 'รถเครน 35 ตัน'), ('รถเครน 45 ตัน', 'รถเครน 45 ตัน'), ('รถเครน >45 ตัน', 'รถเครน >45 ตัน'), ('รถเฮี๊ยบ', 'รถเฮี๊ยบ'), ('รถตัก', 'รถตัก'), ('รถน้ำ', 'รถน้ำ'), ('รถสิบล้อ(ดั๊มพ์+มีฝาท้าย)', 'รถสิบล้อ(ดั๊มพ์+มีฝาท้าย)'), ('รถสิบล้อ(ดั๊มพ์+ไม่มีฝาท้าย)', 'รถสิบล้อ(ดั๊มพ์+ไม่มีฝาท้าย)'), ('รถแบ็คโฮ', 'รถแบ็คโฮ'), ('รถไถ', 'รถไถ'), ('โฟล์คลิฟ', 'โฟล์คลิฟ'), ('รถห่างปลา', 'รถห่างปลา')], max_length=50, verbose_name='ประเภทเครื่องจักร')),
                ('job_description', models.CharField(max_length=100, verbose_name='ลักษณะงาน')),
                ('location', models.CharField(max_length=255, verbose_name='สถานที่')),
                ('contact_number', models.CharField(max_length=20, verbose_name='เบอร์ติดต่อ')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'การจองรถบริการ',
                'verbose_name_plural': 'รายการจองรถบริการ',
                'ordering': ['date_needed', 'start_time'],
            },
        ),
    ]
