# Generated by Django 5.2.3 on 2026-09-14 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0089_vehicle_vehiclebooking'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehiclebooking',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='myapp.vehicle', verbose_name='รถคันที่ใช้งาน (ถ้าระบุ)'),
        ),
    ]
