# Generated by Django 6.1.1 on 2026-09-17 09:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0090_vehiclebooking_vehicle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='กำหนดคืน (กรณียืมข้ามแผนก)'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='to_department',
            field=models.CharField(blank=True, choices=[('mill_a', 'ลูกหีบ A'), ('mill_b', 'ลูกหีบ B'), ('boiler_20', 'หม้อน้ำ 20 bar'), ('boiler_40', 'หม้อน้ำ 40 bar'), ('maintenance', 'ซ่อมบำรุงเครื่องกล'), ('lathe', 'โรงกลึง')], max_length=20, null=True, verbose_name='แผนกผู้ยืม'),
        ),
        migrations.AddField(
            model_name='toolunit',
            name='department',
            field=models.CharField(choices=[('mill_a', 'ลูกหีบ A'), ('mill_b', 'ลูกหีบ B'), ('boiler_20', 'หม้อน้ำ 20 bar'), ('boiler_40', 'หม้อน้ำ 40 bar'), ('maintenance', 'ซ่อมบำรุงเครื่องกล'), ('lathe', 'โรงกลึง')], default='maintenance', max_length=20, verbose_name='แผนกเจ้าของ'),
        ),
        migrations.AddField(
            model_name='toolunit',
            name='maintenance_interval_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ความถี่บำรุงรักษา (วัน)'),
        ),
        migrations.AddField(
            model_name='toolunit',
            name='next_maintenance_due',
            field=models.DateField(blank=True, null=True, verbose_name='กำหนดบำรุงรักษาครั้งถัดไป'),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='tx_type',
            field=models.CharField(choices=[('receive', 'รับเข้า'), ('issue', 'เบิกออก'), ('return', 'คืน'), ('adjust', 'ปรับยอด'), ('loan_out', 'ยืมออก (ข้ามแผนก)'), ('loan_return', 'คืนของยืม (ข้ามแผนก)')], max_length=12, verbose_name='ประเภท'),
        ),
        migrations.CreateModel(
            name='ToolMaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_type', models.CharField(choices=[('repair', 'ซ่อม'), ('pm', 'บำรุงรักษาเชิงป้องกัน (PM)')], default='repair', max_length=10, verbose_name='ประเภท')),
                ('date', models.DateField(verbose_name='วันที่ดำเนินการ')),
                ('technician', models.CharField(max_length=100, verbose_name='ผู้ดำเนินการ')),
                ('description', models.TextField(blank=True, verbose_name='รายละเอียด')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='ค่าใช้จ่าย')),
                ('next_due_date', models.DateField(blank=True, null=True, verbose_name='กำหนดครั้งถัดไป')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tool_maintenance_logs', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
                ('tool_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_logs', to='myapp.toolunit', verbose_name='หน่วยเครื่องมือ')),
            ],
            options={
                'verbose_name': 'บันทึกซ่อมบำรุงเครื่องมือ (Tool Maintenance Log)',
                'verbose_name_plural': 'บันทึกซ่อมบำรุงเครื่องมือ (Tool Maintenance Logs)',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
