# Generated by Django 6.1.1 on 2026-09-17 09:50

from django.db import migrations


def backfill_tool_unit_department(apps, schema_editor):
    """เครื่องมือที่มีอยู่เดิม: ตั้ง ToolUnit.department ให้ตรงกับ item.department เดิม
       (ก่อนหน้านี้แผนกเจ้าของผูกอยู่ที่ระดับชนิดเครื่องมือ ไม่ใช่ระดับหน่วยรายชิ้น)"""
    ToolUnit = apps.get_model('myapp', 'ToolUnit')
    for unit in ToolUnit.objects.select_related('item').all():
        unit.department = unit.item.department
        unit.save(update_fields=['department'])


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0091_inventorytransaction_due_date_and_more'),
    ]

    operations = [
        migrations.RunPython(backfill_tool_unit_department, migrations.RunPython.noop),
    ]
