# Generated by Django 6.1.1 on 2026-09-17 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0092_backfill_toolunit_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolreadinesscheck',
            name='safety_ok',
            field=models.BooleanField(default=True, verbose_name='ทำความสะอาดเรียบร้อย'),
        ),
    ]
