# Generated by Django 6.1.1 on 2026-09-21 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0093_alter_toolreadinesscheck_safety_ok'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('write_boiler', 'เขียนข้อมูล: หม้อไอน้ำ (Boiler)'), ('write_equipment', 'เขียนข้อมูล: เครื่องจักร/อะไหล่/PM/ใบสั่งงาน'), ('write_cbm', 'เขียนข้อมูล: ตรวจสภาพเครื่องจักร (CBM)'), ('write_maintenance', 'เขียนข้อมูล: แจ้งซ่อม/บันทึกปัญหาเครื่องจักร'), ('write_mill', 'เขียนข้อมูล: ลูกหีบ/การผลิต (Mill)'), ('write_docs', 'เขียนข้อมูล: คลังเอกสารงานซ่อม'), ('write_inventory', 'เขียนข้อมูล: คลังพัสดุ (Inventory)'), ('write_tools', 'เขียนข้อมูล: เครื่องมือ (Tools)'), ('write_training', 'เขียนข้อมูล: ศูนย์การเรียนรู้ (Training)'), ('write_general', 'เขียนข้อมูล: งานทั่วไป (คู่มือ/งานมอบหมาย/จองรถ/โรงกลึง)')]},
        ),
    ]
