# Generated by Django 6.1.1 on 2026-09-21

from django.db import migrations

MODULE_GROUPS = [
    ('boiler', 'Boiler Staff', 'เขียนข้อมูล: หม้อไอน้ำ (Boiler)'),
    ('equipment', 'Equipment Staff', 'เขียนข้อมูล: เครื่องจักร/อะไหล่/PM/ใบสั่งงาน'),
    ('cbm', 'CBM Staff', 'เขียนข้อมูล: ตรวจสภาพเครื่องจักร (CBM)'),
    ('maintenance', 'Maintenance Staff', 'เขียนข้อมูล: แจ้งซ่อม/บันทึกปัญหาเครื่องจักร'),
    ('mill', 'Mill Staff', 'เขียนข้อมูล: ลูกหีบ/การผลิต (Mill)'),
    ('docs', 'Docs Staff', 'เขียนข้อมูล: คลังเอกสารงานซ่อม'),
    ('inventory', 'Inventory Staff', 'เขียนข้อมูล: คลังพัสดุ (Inventory)'),
    ('tools', 'Tools Staff', 'เขียนข้อมูล: เครื่องมือ (Tools)'),
    ('training', 'Training Staff', 'เขียนข้อมูล: ศูนย์การเรียนรู้ (Training)'),
    ('general', 'General Staff', 'เขียนข้อมูล: งานทั่วไป (คู่มือ/งานมอบหมาย/จองรถ/โรงกลึง)'),
]


def seed_module_groups(apps, schema_editor):
    """สร้าง Group ต่อ module พร้อมผูก permission ที่ตรงกัน
       แล้วเพิ่ม staff เดิมทุกคนเข้าทุก Group เพื่อไม่ให้เสียสิทธิ์เขียนข้อมูลที่เคยมีอยู่แล้ว"""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    User = apps.get_model('auth', 'User')

    # post_migrate (create_contenttypes) ยังไม่ทันรันตอนนี้เช่นกัน จึงสร้าง ContentType เองถ้ายังไม่มี
    profile_ct, _ = ContentType.objects.get_or_create(app_label='myapp', model='profile')

    groups = []
    for module_key, group_name, perm_name in MODULE_GROUPS:
        group, _ = Group.objects.get_or_create(name=group_name)
        # post_migrate (create_permissions) ยังไม่ทันรันตอนนี้ จึงสร้าง Permission เองถ้ายังไม่มี
        perm, _ = Permission.objects.get_or_create(
            content_type=profile_ct,
            codename=f'write_{module_key}',
            defaults={'name': perm_name},
        )
        group.permissions.add(perm)
        groups.append(group)

    for user in User.objects.filter(is_staff=True, is_superuser=False):
        user.groups.add(*groups)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0094_profile_module_permissions'),
    ]

    operations = [
        migrations.RunPython(seed_module_groups, migrations.RunPython.noop),
    ]
