# Generated by Django 6.1.1 on 2026-09-21 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0095_seed_module_groups'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('write_boiler', 'เขียนข้อมูล: หม้อไอน้ำ (Boiler)'), ('write_equipment', 'เขียนข้อมูล: เครื่องจักร/อะไหล่/PM/ใบสั่งงาน'), ('write_cbm', 'เขียนข้อมูล: ตรวจสภาพเครื่องจักร (CBM)'), ('write_maintenance', 'เขียนข้อมูล: แจ้งซ่อม/บันทึกปัญหาเครื่องจักร'), ('write_mill', 'เขียนข้อมูล: ลูกหีบ/การผลิต (Mill)'), ('write_docs', 'เขียนข้อมูล: คลังเอกสารงานซ่อม'), ('write_inventory', 'เขียนข้อมูล: คลังพัสดุ (Inventory)'), ('write_tools', 'เขียนข้อมูล: เครื่องมือ (Tools)'), ('write_training', 'เขียนข้อมูล: ศูนย์การเรียนรู้ (Training)'), ('write_general', 'เขียนข้อมูล: งานทั่วไป (คู่มือ/งานมอบหมาย/จองรถ/โรงกลึง)'), ('write_energy', 'เขียนข้อมูล: พลังงาน (ไฟฟ้า/ไอน้ำ)')]},
        ),
        migrations.CreateModel(
            name='ElectricityMeter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_code', models.CharField(max_length=50, unique=True, verbose_name='รหัสมิเตอร์')),
                ('name', models.CharField(max_length=255, verbose_name='ชื่อมิเตอร์')),
                ('plant', models.CharField(choices=[('ESC-A', 'ESC-A'), ('ESC-B', 'ESC-B')], max_length=10, verbose_name='Plant')),
                ('process', models.CharField(blank=True, max_length=255, null=True, verbose_name='กระบวนการ')),
                ('assumed_operating_hours', models.DecimalField(blank=True, decimal_places=2, default=24.0, max_digits=5, null=True, verbose_name='ชั่วโมงทำงานที่ใช้คำนวณ (ชม./วัน)')),
                ('target_kwh_override', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='กำหนด kWh(Max) เอง (ถ้าไม่กำหนด ระบบคำนวณอัตโนมัติ)')),
                ('is_active', models.BooleanField(default=True, verbose_name='สถานะใช้งาน')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_meters_created', to=settings.AUTH_USER_MODEL, verbose_name='ผู้สร้าง')),
                ('equipment', models.ManyToManyField(blank=True, related_name='electricity_meters', to='myapp.equipment', verbose_name='เครื่องจักรที่ผูกกับมิเตอร์นี้')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_meters_updated', to=settings.AUTH_USER_MODEL, verbose_name='ผู้แก้ไขล่าสุด')),
            ],
            options={
                'verbose_name': 'มิเตอร์ไฟฟ้า',
                'verbose_name_plural': 'มิเตอร์ไฟฟ้าทั้งหมด',
                'ordering': ['plant', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ElectricityReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='วันที่')),
                ('reading_kwh', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='เลขมิเตอร์สะสม (kWh)')),
                ('is_meter_reset', models.BooleanField(default=False, verbose_name='เปลี่ยน/รีเซ็ตมิเตอร์วันนี้')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='หมายเหตุ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='readings', to='myapp.electricitymeter', verbose_name='มิเตอร์')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electricity_readings', to=settings.AUTH_USER_MODEL, verbose_name='ผู้บันทึก')),
            ],
            options={
                'verbose_name': 'ค่ามิเตอร์ไฟฟ้ารายวัน',
                'verbose_name_plural': 'ค่ามิเตอร์ไฟฟ้ารายวันทั้งหมด',
                'ordering': ['-date'],
                'constraints': [models.UniqueConstraint(fields=('meter', 'date'), name='uniq_electricity_reading_meter_date')],
            },
        ),
    ]
