# Generated by Django 6.1.1 on 2026-09-21

from django.db import migrations


def seed_energy_group(apps, schema_editor):
    """สร้าง Group 'Energy Staff' ผูก permission write_energy
       แล้วเพิ่ม staff เดิมทุกคนเข้ากลุ่มนี้ เพื่อไม่ให้เสียสิทธิ์เขียนข้อมูลที่เคยมีอยู่แล้ว
       (รูปแบบเดียวกับ 0095_seed_module_groups.py)"""
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    User = apps.get_model('auth', 'User')

    profile_ct, _ = ContentType.objects.get_or_create(app_label='myapp', model='profile')

    group, _ = Group.objects.get_or_create(name='Energy Staff')
    perm, _ = Permission.objects.get_or_create(
        content_type=profile_ct,
        codename='write_energy',
        defaults={'name': 'เขียนข้อมูล: พลังงาน (ไฟฟ้า/ไอน้ำ)'},
    )
    group.permissions.add(perm)

    for user in User.objects.filter(is_staff=True, is_superuser=False):
        user.groups.add(group)


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0096_electricitymeter_electricityreading'),
    ]

    operations = [
        migrations.RunPython(seed_energy_group, migrations.RunPython.noop),
    ]
