# Generated by Django 6.1.1 on 2026-09-22 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0097_seed_energy_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='electricitymeter',
            name='process',
        ),
        migrations.AddField(
            model_name='electricitymeter',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='สถานที่ตั้ง'),
        ),
    ]
