# Generated by Django 6.1.1 on 2026-09-25 03:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0098_electricitymeter_rename_process_to_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SteamLeakTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่องาน')),
                ('assignee', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้รับผิดชอบ')),
                ('status', models.CharField(choices=[('wait', 'รอดำเนินการ'), ('todo', 'เตรียมการ'), ('doing', 'กำลังทดสอบ'), ('done', 'เสร็จสิ้น')], default='wait', max_length=10, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/ปัญหา')),
                ('inspection_date', models.DateField(blank=True, null=True, verbose_name='วันที่ตรวจสอบ')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้แก้ไขล่าสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steam_leak_tests', to='myapp.equipment', verbose_name='เครื่องจักร')),
            ],
            options={
                'verbose_name': 'ทดสอบระบบไอน้ำ (ตรวจรอยรั่ว)',
                'verbose_name_plural': 'ทดสอบระบบไอน้ำ (ตรวจรอยรั่ว)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SteamLeakCheckItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_topic', models.CharField(max_length=255, verbose_name='หัวข้อตรวจสอบ')),
                ('check_item', models.CharField(max_length=255, verbose_name='รายการตรวจสอบ')),
                ('standard', models.CharField(blank=True, max_length=255, null=True, verbose_name='มาตรฐานการตรวจสอบ')),
                ('result', models.CharField(choices=[('normal', 'ปกติ'), ('abnormal', 'ผิดปกติ')], default='normal', max_length=10, verbose_name='ผลตรวจสอบ')),
                ('cause', models.TextField(blank=True, null=True, verbose_name='สาเหตุ (หากผิดปกติ)')),
                ('corrective_action', models.TextField(blank=True, null=True, verbose_name='วิธีการแก้ไข')),
                ('fix_due_date', models.DateField(blank=True, null=True, verbose_name='วันที่กำหนดแก้ไขเสร็จ')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_items', to='myapp.steamleaktest', verbose_name='งานทดสอบ')),
            ],
            options={
                'verbose_name': 'รายการตรวจรอยรั่วไอน้ำ',
                'verbose_name_plural': 'รายการตรวจรอยรั่วไอน้ำ',
                'ordering': ['test', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='WaterCIPTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่องาน')),
                ('assignee', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้รับผิดชอบ')),
                ('status', models.CharField(choices=[('wait', 'รอดำเนินการ'), ('todo', 'เตรียมการ'), ('doing', 'กำลังทดสอบ'), ('done', 'เสร็จสิ้น')], default='wait', max_length=10, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/ปัญหา')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='วันที่ทดสอบ')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='เวลาเริ่มบันทึก')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='เวลาสิ้นสุดบันทึก')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้แก้ไขล่าสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('end_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cip_tests_end', to='myapp.equipment', verbose_name='เครื่องจักรปลายทาง')),
                ('start_equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cip_tests_start', to='myapp.equipment', verbose_name='เครื่องจักรต้นทาง')),
            ],
            options={
                'verbose_name': 'ทดสอบระบบน้ำ (CIP)',
                'verbose_name_plural': 'ทดสอบระบบน้ำ (CIP)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WaterCIPPhReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_time', models.TimeField(blank=True, null=True, verbose_name='เวลาที่บันทึก')),
                ('ph_value', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='ค่า pH')),
                ('point_label', models.CharField(blank=True, max_length=100, null=True, verbose_name='จุดที่วัด (ถ้ามี)')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ph_readings', to='myapp.waterciptest', verbose_name='งานทดสอบ')),
            ],
            options={
                'verbose_name': 'ค่า pH การทดสอบระบบน้ำ',
                'verbose_name_plural': 'ค่า pH การทดสอบระบบน้ำ',
                'ordering': ['test', 'display_order'],
            },
        ),
    ]
