# Generated by Django 6.1.1 on 2026-09-25 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0099_steamleaktest_steamleakcheckitem_waterciptest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlushingTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='ชื่องาน')),
                ('assignee', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้รับผิดชอบ')),
                ('status', models.CharField(choices=[('wait', 'รอดำเนินการ'), ('todo', 'เตรียมการ'), ('doing', 'กำลังทดสอบ'), ('done', 'เสร็จสิ้น')], default='wait', max_length=10, verbose_name='สถานะ')),
                ('note', models.TextField(blank=True, null=True, verbose_name='หมายเหตุ/ปัญหา')),
                ('test_date', models.DateField(blank=True, null=True, verbose_name='วันที่ทดสอบ')),
                ('pipe_surface_temp_c', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='อุณหภูมิผิวท่อที่วัดได้ (°C)')),
                ('updated_by', models.CharField(blank=True, max_length=100, null=True, verbose_name='ผู้แก้ไขล่าสุด')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flushing_tests', to='myapp.equipment', verbose_name='ท่อ/เครื่องจักร')),
            ],
            options={
                'verbose_name': 'ทดสอบเป่าแป๊ป (Flushing)',
                'verbose_name_plural': 'ทดสอบเป่าแป๊ป (Flushing)',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FlushingRound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_no', models.PositiveIntegerField(blank=True, null=True, verbose_name='ครั้งที่เป่า')),
                ('has_copper_plate', models.BooleanField(default=True, verbose_name='ใส่แผ่นทองแดง')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='เวลาเริ่มเป่า')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='เวลาเป่าเสร็จ')),
                ('blow_pressure_bar', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='แรงดันที่ใช้เป่า (bar)')),
                ('oversized_spot_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='จำนวนจุดขนาด > 0.3 mm ที่พบ (จุด/cm²)')),
                ('note', models.CharField(blank=True, max_length=255, null=True, verbose_name='หมายเหตุรอบนี้')),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rounds', to='myapp.flushingtest', verbose_name='งานทดสอบ')),
            ],
            options={
                'verbose_name': 'รอบการเป่าแป๊ป',
                'verbose_name_plural': 'รอบการเป่าแป๊ป',
                'ordering': ['test', 'display_order'],
            },
        ),
    ]
