# Generated by Django 6.1.1 on 2026-09-26 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0100_flushingtest_flushinground'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='department',
            field=models.CharField(blank=True, choices=[('ฝ่ายวิศวกรรมจักรกล', [('ลูกหีบ', 'ลูกหีบ (Mill)'), ('หม้อน้ำ', 'หม้อน้ำ (Boiler)'), ('ซ่อมบำรุงเครื่องกล', 'ซ่อมบำรุงเครื่องกล (Mechanical)'), ('โรงกลึง', 'โรงกลึง (Lathe)')]), ('ฝ่ายผลิต', [('หม้อต้ม', 'หม้อต้ม (Evaporator)'), ('หม้อเคี่ยว', 'หม้อเคี่ยว (Vacuum Pan)'), ('หม้อปั่น', 'หม้อปั่น (Centrifuge)'), ('รีไฟน์', 'รีไฟน์ (Refine)')])], default='', max_length=50, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='manual',
            name='department',
            field=models.CharField(choices=[('ฝ่ายวิศวกรรมจักรกล', [('ลูกหีบ', 'ลูกหีบ (Mill)'), ('หม้อน้ำ', 'หม้อน้ำ (Boiler)'), ('ซ่อมบำรุงเครื่องกล', 'ซ่อมบำรุงเครื่องกล (Mechanical)'), ('โรงกลึง', 'โรงกลึง (Lathe)')]), ('ฝ่ายผลิต', [('หม้อต้ม', 'หม้อต้ม (Evaporator)'), ('หม้อเคี่ยว', 'หม้อเคี่ยว (Vacuum Pan)'), ('หม้อปั่น', 'หม้อปั่น (Centrifuge)'), ('รีไฟน์', 'รีไฟน์ (Refine)')])], max_length=50, verbose_name='แผนก'),
        ),
        migrations.AlterField(
            model_name='repairdocument',
            name='department',
            field=models.CharField(choices=[('ฝ่ายวิศวกรรมจักรกล', [('ลูกหีบ', 'ลูกหีบ (Mill)'), ('หม้อน้ำ', 'หม้อน้ำ (Boiler)'), ('ซ่อมบำรุงเครื่องกล', 'ซ่อมบำรุงเครื่องกล (Mechanical)'), ('โรงกลึง', 'โรงกลึง (Lathe)')]), ('ฝ่ายผลิต', [('หม้อต้ม', 'หม้อต้ม (Evaporator)'), ('หม้อเคี่ยว', 'หม้อเคี่ยว (Vacuum Pan)'), ('หม้อปั่น', 'หม้อปั่น (Centrifuge)'), ('รีไฟน์', 'รีไฟน์ (Refine)')])], max_length=50, verbose_name='แผนก'),
        ),
    ]
