# Generated by Django 6.1.1 on 2026-10-08 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0102_alter_employee_department_alter_manual_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='รูปภาพพนักงาน'),
        ),
    ]
