# Generated by Django 6.1.1 on 2026-10-08 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0103_employee_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lathejob',
            options={'ordering': ['-date', '-id'], 'verbose_name': 'ใบสั่งงานโรงกลึง', 'verbose_name_plural': 'ใบสั่งงานโรงกลึง'},
        ),
        migrations.AddField(
            model_name='lathejob',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='lathejob',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='lathejob',
            name='updated_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='hours',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='เวลาทำงานรวม (ชม.)'),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='ค่าวัสดุ'),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='pieces',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=8, null=True, verbose_name='จำนวน (ชิ้น)'),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='plan_status',
            field=models.CharField(blank=True, choices=[('Accepted', 'รับงาน'), ('Rejected', 'ไม่รับงาน')], max_length=50, null=True, verbose_name='สถานะพิจารณา'),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='priority',
            field=models.CharField(blank=True, choices=[('Breakdown', 'A: เครื่องจักรหยุด (Breakdown)'), ('Urgent', 'B: ด่วน (Urgent) - ภายใน 24 ชม.'), ('Normal', 'C: ปกติ (Normal) - ตามคิวงาน')], max_length=50, null=True, verbose_name='ความเร่งด่วน'),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='qc_result',
            field=models.CharField(blank=True, choices=[('Pass', 'ผ่าน (Pass)'), ('Fail', 'ไม่ผ่าน (Fail)')], max_length=50, null=True, verbose_name='ผล QC'),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='status',
            field=models.CharField(choices=[('Pending', 'รอรับงาน'), ('In Progress', 'กำลังทำ'), ('Done', 'เสร็จสิ้น'), ('Rejected', 'ไม่รับ')], default='Pending', max_length=50, verbose_name='สถานะงาน'),
        ),
    ]
