# Generated by Django 6.1.1 on 2026-10-09 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0104_lathejob_cleanup'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lathejob',
            name='has_drawing',
        ),
        migrations.RemoveField(
            model_name='lathejob',
            name='has_material',
        ),
        migrations.RemoveField(
            model_name='lathejob',
            name='has_sample',
        ),
        migrations.AddField(
            model_name='lathejob',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='ชื่อไฟล์แนบ'),
        ),
        migrations.AddField(
            model_name='lathejob',
            name='job_value',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='มูลค่าชิ้นงาน (บาท)'),
        ),
        migrations.AddField(
            model_name='lathejob',
            name='labor_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='ค่าแรง'),
        ),
        migrations.AddField(
            model_name='lathejob',
            name='machine_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='ค่าเครื่องจักร'),
        ),
        migrations.AddField(
            model_name='lathejob',
            name='service_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='ค่าดำเนินการ'),
        ),
        migrations.AlterField(
            model_name='lathejob',
            name='material_cost',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True, verbose_name='ค่าวัสดุ'),
        ),
    ]
